## 1️⃣ PREPARAÇÃO DOS DADOS

In [1]:
install.packages(c(
  "readxl", "lavaan", "semTools", "psych",
  "tidyverse", "blavaan", "bayesplot"
))

library(readxl)
library(lavaan)
library(semTools)
library(psych)
library(tidyverse)
library(blavaan)
library(bayesplot)

Instalando pacotes em 'C:/Users/Maxwell/AppData/Local/R/win-library/4.5'
(como 'lib' não foi especificado)

pacote 'readxl' desempacotado com sucesso e somas MD5 verificadas
pacote 'lavaan' desempacotado com sucesso e somas MD5 verificadas
pacote 'semTools' desempacotado com sucesso e somas MD5 verificadas
pacote 'psych' desempacotado com sucesso e somas MD5 verificadas
pacote 'tidyverse' desempacotado com sucesso e somas MD5 verificadas
pacote 'blavaan' desempacotado com sucesso e somas MD5 verificadas
pacote 'bayesplot' desempacotado com sucesso e somas MD5 verificadas

Os pacotes binários baixados estão em
	C:\Users\Maxwell\AppData\Local\Temp\RtmpoBBIEl\downloaded_packages

This is lavaan 0.6-21
lavaan is FREE software! Please report any bugs.



###############################################################################

This is semTools 0.5-7

All users of R (or SEM) are invited to submit functions or ideas for functions.

###############################################################################


Anexando pacote: 'psych'


Os seguintes objetos são mascarados por 'package:semTools':

    reliability, skew


O seguinte objeto é mascarado por 'package:lavaan':

    cor2cov


── Attaching core tidyverse packages ──────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.1     ✔ tibble    3.3.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.2
✔ purrr     1.2.1
── Conflicts ────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ ggplot2::%+%()     masks psych::%+%()
✖ ggplot2::alpha()   masks psych::alpha()
✖ readr::clipboard() masks semTools::clipboard()
✖ dplyr::filter()    masks stats::filter()
✖ dplyr::lag()       masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Carregando pacotes exigidos: Rcpp

This is blavaan 0.5-10

On multicore systems, we suggest use of future::plan("multicore") or
  future::plan("multisession") for faster post-MCMC computations.

This is bayesplot version 1.15.0

- Online documentation and vignettes at mc-stan.org/bayesplot

- bayesplot theme set to bayesplot::theme_default()

   * Does _not_ affect other ggplot2 plots

   * See ?bayesplot_theme_set for details on theme setting

In [2]:
dados <- read_excel("dados-cp.xlsx")

In [5]:
colnames(dados) <- paste0("Q", 1:72)

## 2️⃣ ESPECIFICAÇÃO TEÓRICA DO MODELO DE AFC

In [3]:
modelo_emocional <- '
Consciencia_Emocional =~ Q48 + Q49 + Q50 + Q51 + Q52 + Q53 + Q54

Regulacao_Emocional =~ Q55 + Q56 + Q57 + Q58 + Q59 + Q60

Consciencia_Social =~ Q61 + Q62 + Q63 + Q64

Autocontrole_Emocional =~ Q65 + Q66 + Q67

Criatividade_Emocional =~ Q68 + Q69 + Q70 + Q71 + Q72
'

In [44]:
modelo_trabalho <- '
Autonomia_Variedade =~ Q6 + Q7 + Q8 + Q9 + Q10 + Q11

Signif_Identif_Feedback =~ Q12 + Q13 + Q14 + Q15 + Q16 + Q17 + Q18

Complexidade_Proc_Criativ =~ Q19 + Q20 + Q21 + Q22 + Q23 + Q24 + Q25 + Q26 + Q27

Apoio_Interdep_Interacao =~ Q28 + Q29 + Q30 + Q31 + Q32 + Q33 + Q34 + Q35 + Q36 + Q37

Exig_Fisicas_Ambiente =~ Q38 + Q39 + Q40 + Q41 + Q42 + Q43 + Q44 + Q45 + Q46 + Q47
'

## 3️⃣ AFC ROBUSTA (MLR)

In [6]:
fit_emocional <- cfa(
  modelo_emocional,
  data = dados,
  estimator = "MLR",
  std.lv = TRUE,
  missing = "fiml"
)

In [47]:
fitMeasures(fit_emocional, c(
  "chisq","df","pvalue","cfi","tli","rmsea","rmsea.ci.lower","rmsea.ci.upper","srmr"
))

         chisq             df         pvalue            cfi            tli
       774.699        265.000          0.000          0.919          0.908
         rmsea rmsea.ci.lower rmsea.ci.upper           srmr
         0.077          0.071          0.084          0.050

In [45]:
fit_trabalho <- cfa(
  modelo_trabalho,
  data = dados,
  estimator = "MLR",
  std.lv = TRUE,
  missing = "fiml"
)

In [48]:
fitMeasures(fit_trabalho, c(
  "chisq","df","pvalue","cfi","tli","rmsea","rmsea.ci.lower","rmsea.ci.upper","srmr"
))

         chisq             df         pvalue            cfi            tli
      3453.499        809.000          0.000          0.592          0.566
         rmsea rmsea.ci.lower rmsea.ci.upper           srmr
         0.101          0.097          0.104          0.113

## 5️⃣ CARGAS FATORIAIS E CONFIABILIDADE

In [8]:
standardizedSolution(fit_emocional) %>% filter(op == "=~")

   lhs                    op rhs est.std   se         z        pvalue ci.lower
1  Consciencia_Emocional  =~ Q48 0.8372264 0.02738787 30.56924 0      0.7835471
2  Consciencia_Emocional  =~ Q49 0.7798641 0.03539036 22.03606 0      0.7105003
3  Consciencia_Emocional  =~ Q50 0.7693456 0.03734382 20.60169 0      0.6961530
4  Consciencia_Emocional  =~ Q51 0.7930523 0.03664725 21.64016 0      0.7212250
5  Consciencia_Emocional  =~ Q52 0.7875459 0.03922618 20.07705 0      0.7106640
6  Consciencia_Emocional  =~ Q53 0.6945339 0.04341919 15.99601 0      0.6094339
7  Consciencia_Emocional  =~ Q54 0.7203988 0.04922080 14.63607 0      0.6239278
8  Regulacao_Emocional    =~ Q55 0.7147904 0.03908189 18.28956 0      0.6381913
9  Regulacao_Emocional    =~ Q56 0.7698734 0.03778729 20.37387 0      0.6958116
10 Regulacao_Emocional    =~ Q57 0.7412442 0.03554703 20.85249 0      0.6715733
11 Regulacao_Emocional    =~ Q58 0.7438434 0.04243032 17.53094 0      0.6606815
12 Regulacao_Emocional    =~ Q59 0.8393341 0.03120993 26.89317 0      0.7781637
13 Regulacao_Emocional    =~ Q60 0.8244076 0.03648506 22.59576 0      0.7528982
14 Consciencia_Social     =~ Q61 0.8571446 0.03303472 25.94678 0      0.7923977
15 Consciencia_Social     =~ Q62 0.9037248 0.03336533 27.08574 0      0.8383299
16 Consciencia_Social     =~ Q63 0.9013004 0.02279662 39.53658 0      0.8566199
17 Consciencia_Social     =~ Q64 0.8641355 0.02700967 31.99356 0      0.8111975
18 Autocontrole_Emocional =~ Q65 0.9066494 0.01742790 52.02287 0      0.8724914
19 Autocontrole_Emocional =~ Q66 0.8587772 0.02836916 30.27151 0      0.8031747
20 Autocontrole_Emocional =~ Q67 0.8673744 0.03077615 28.18333 0      0.8070542
21 Criatividade_Emocional =~ Q68 0.7431976 0.03559339 20.88022 0      0.6734358
22 Criatividade_Emocional =~ Q69 0.8552013 0.02977147 28.72553 0      0.7968503
23 Criatividade_Emocional =~ Q70 0.8310177 0.02728972 30.45168 0      0.7775309
24 Criatividade_Emocional =~ Q71 0.7954697 0.03168527 25.10535 0      0.7333677
25 Criatividade_Emocional =~ Q72 0.7854691 0.03319693 23.66089 0      0.7204043
   ci.upper
1  0.8909056
2  0.8492280
3  0.8425381
4  0.8648796
5  0.8644278
6  0.7796340
7  0.8168698
8  0.7913895
9  0.8439351
10 0.8109151
11 0.8270053
12 0.9005044
13 0.8959170
14 0.9218914
15 0.9691196
16 0.9459810
17 0.9170735
18 0.9408075
19 0.9143797
20 0.9276945
21 0.8129593
22 0.9135523
23 0.8845046
24 0.8575716
25 0.8505339

In [9]:
semTools::reliability(fit_emocional)

Warning message in semTools::reliability(fit_emocional):
"
The reliability() function was deprecated in 2022 and will cease to be included in future versions of semTools. See help('semTools-deprecated) for details.

It is replaced by the compRelSEM() function, which can estimate alpha and model-based reliability in an even wider variety of models and data types, with greater control in specifying the desired type of reliability coefficient (i.e., more explicitly choosing assumptions).

The average variance extracted should never have been included because it is not a reliability coefficient. It is now available from the AVE() function."

       Consciencia_Emocional Regulacao_Emocional Consciencia_Social
alpha  0.9093936             0.8974019           0.9315357
omega  0.9090518             0.8970471           0.9325157
omega2 0.9090518             0.8970471           0.9325157
omega3 0.9068019             0.8946099           0.9345366
avevar 0.5885939             0.5928338           0.7755733
       Autocontrole_Emocional Criatividade_Emocional
alpha  0.9096510              0.8984723
omega  0.9104219              0.8992509
omega2 0.9104219              0.8992509
omega3 0.9096524              0.9006337
avevar 0.7725860              0.6411947

In [10]:
semTools::compRelSEM(fit_emocional)

 Consciencia_Emocional    Regulacao_Emocional     Consciencia_Social
                 0.907                  0.895                  0.935
Autocontrole_Emocional Criatividade_Emocional
                 0.910                  0.901

## 6️⃣ VALIDADE DISCRIMINANTE

In [11]:
cor_lat <- inspect(fit_emocional, "cor.lv")
sqrt_ave <- sqrt(AVE(fit_emocional))

sqrt_ave > cor_lat

                       Consciencia_Emocional Regulacao_Emocional
Consciencia_Emocional  FALSE                  TRUE
Regulacao_Emocional     TRUE                 FALSE
Consciencia_Social      TRUE                  TRUE
Autocontrole_Emocional  TRUE                  TRUE
Criatividade_Emocional  TRUE                  TRUE
                       Consciencia_Social Autocontrole_Emocional
Consciencia_Emocional   TRUE               TRUE
Regulacao_Emocional     TRUE               TRUE
Consciencia_Social     FALSE               TRUE
Autocontrole_Emocional  TRUE              FALSE
Criatividade_Emocional  TRUE               TRUE
                       Criatividade_Emocional
Consciencia_Emocional   TRUE
Regulacao_Emocional     TRUE
Consciencia_Social      TRUE
Autocontrole_Emocional  TRUE
Criatividade_Emocional FALSE

In [12]:
cor_lat

                       Consciencia_Emocional Regulacao_Emocional
Consciencia_Emocional  1.0000000             0.6060820
Regulacao_Emocional    0.6060820             1.0000000
Consciencia_Social     0.6144183             0.6236851
Autocontrole_Emocional 0.5618464             0.5870554
Criatividade_Emocional 0.6941836             0.6688011
                       Consciencia_Social Autocontrole_Emocional
Consciencia_Emocional  0.6144183          0.5618464
Regulacao_Emocional    0.6236851          0.5870554
Consciencia_Social     1.0000000          0.7422725
Autocontrole_Emocional 0.7422725          1.0000000
Criatividade_Emocional 0.7188923          0.6709174
                       Criatividade_Emocional
Consciencia_Emocional  0.6941836
Regulacao_Emocional    0.6688011
Consciencia_Social     0.7188923
Autocontrole_Emocional 0.6709174
Criatividade_Emocional 1.0000000

In [13]:
sqrt_ave

 Consciencia_Emocional    Regulacao_Emocional     Consciencia_Social
                 0.767                  0.770                  0.881
Autocontrole_Emocional Criatividade_Emocional
                 0.879                  0.801

## 7️⃣ ANÁLISE BAYESIANA FATORIAL

In [14]:
fit_bayes_emocional <- bcfa(
  modelo_emocional,
  data = dados,
  burnin = 2000,
  sample = 5000,
  n.chains = 4
)

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 1).
Chain 1:
Chain 1: Gradient evaluation took 0.003908 seconds
Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 39.08 seconds.
Chain 1: Adjust your expectations accordingly!
Chain 1:
Chain 1:
Chain 1: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 1: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 1: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 1: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 1: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 1: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 1: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 1: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 1: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 1: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 1: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 1: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 1:
Chain 1:  Elapsed Time: 65.015 seconds (Warm-up)
Chain 1:                154.002 seconds (Sampling)
Chain 1:                219.017 seconds (Total)
Chain 1:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 2).
Chain 2:
Chain 2: Gradient evaluation took 0.003182 seconds
Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 31.82 seconds.
Chain 2: Adjust your expectations accordingly!
Chain 2:
Chain 2:
Chain 2: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 2: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 2: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 2: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 2: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 2: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 2: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 2: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 2: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 2: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 2: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 2: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 2:
Chain 2:  Elapsed Time: 73.89 seconds (Warm-up)
Chain 2:                199.042 seconds (Sampling)
Chain 2:                272.932 seconds (Total)
Chain 2:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 3).
Chain 3:
Chain 3: Gradient evaluation took 0.004241 seconds
Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 42.41 seconds.
Chain 3: Adjust your expectations accordingly!
Chain 3:
Chain 3:
Chain 3: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 3: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 3: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 3: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 3: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 3: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 3: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 3: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 3: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 3: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 3: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 3: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 3:
Chain 3:  Elapsed Time: 60.879 seconds (Warm-up)
Chain 3:                171.957 seconds (Sampling)
Chain 3:                232.836 seconds (Total)
Chain 3:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 4).
Chain 4:
Chain 4: Gradient evaluation took 0.001911 seconds
Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 19.11 seconds.
Chain 4: Adjust your expectations accordingly!
Chain 4:
Chain 4:
Chain 4: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 4: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 4: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 4: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 4: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 4: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 4: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 4: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 4: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 4: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 4: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 4: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 4:
Chain 4:  Elapsed Time: 68.322 seconds (Warm-up)
Chain 4:                166.289 seconds (Sampling)
Chain 4:                234.611 seconds (Total)
Chain 4:
Computing post-estimation metrics (including lvs if requested)...

In [15]:
summary(fit_bayes_emocional)

blavaan 0.5.10 ended normally after 5000 iterations

  Estimator                                      BAYES
  Optimization method                             MCMC
  Number of model parameters                        60

  Number of observations                           323

  Statistic                                 MargLogLik         PPP
  Value                                      -9617.061       0.000

Parameter Estimates:


Latent Variables:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional =~
    Q48                        1.000
    Q49                        1.022    0.065    0.901    1.156    1.000
    Q50                        0.947    0.061    0.831    1.071    1.000
    Q51                        0.941    0.058    0.831    1.060    1.000
    Q52                        0.947    0.058    0.839    1.066    1.000
    Q53                        0.953    0.070    0.820    1.094    1.000
    Q54                        0.888    0.062    0.771    1.014    1.000
  Regulacao_Emocional =~
    Q55                        1.000
    Q56                        0.994    0.077    0.856    1.156    1.000
    Q57                        1.025    0.082    0.875    1.196    1.000
    Q58                        0.892    0.075    0.755    1.051    1.000
    Q59                        1.048    0.079    0.902    1.214    1.000
    Q60                        1.027    0.079    0.882    1.194    1.000
  Consciencia_Social =~
    Q61                        1.000
    Q62                        0.966    0.044    0.885    1.056    1.000
    Q63                        1.012    0.046    0.924    1.106    1.000
    Q64                        0.980    0.049    0.887    1.079    1.000
  Autocontrole_Emocional =~
    Q65                        1.000
    Q66                        0.906    0.042    0.825    0.991    1.000
    Q67                        0.892    0.043    0.810    0.980    1.000
  Criatividade_Emocional =~
    Q68                        1.000
    Q69                        1.058    0.070    0.931    1.205    1.000
    Q70                        1.121    0.077    0.978    1.285    1.000
    Q71                        1.095    0.079    0.952    1.261    1.000
    Q72                        1.078    0.079    0.933    1.244    1.000
    Prior


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)

Covariances:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional ~~
    Regulaca_Emcnl             0.484    0.066    0.364    0.623    1.000
    Conscienci_Scl             0.469    0.058    0.365    0.593    1.000
    Autcntrl_Emcnl             0.520    0.068    0.397    0.661    1.000
    Criatvdd_Emcnl             0.515    0.063    0.401    0.649    1.000
  Regulacao_Emocional ~~
    Conscienci_Scl             0.465    0.061    0.354    0.595    1.000
    Autcntrl_Emcnl             0.532    0.072    0.401    0.685    1.000
    Criatvdd_Emcnl             0.483    0.065    0.365    0.622    1.000
  Consciencia_Social ~~
    Autcntrl_Emcnl             0.650    0.069    0.523    0.796    1.000
    Criatvdd_Emcnl             0.498    0.059    0.391    0.620    1.000
  Autocontrole_Emocional ~~
    Criatvdd_Emcnl             0.565    0.069    0.439    0.707    1.000
    Prior

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)

Variances:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               0.375    0.038    0.306    0.457    1.000 gamma(1,.5)[sd]
   .Q49               0.573    0.053    0.478    0.683    1.000 gamma(1,.5)[sd]
   .Q50               0.526    0.048    0.440    0.627    1.000 gamma(1,.5)[sd]
   .Q51               0.444    0.041    0.369    0.529    1.000 gamma(1,.5)[sd]
   .Q52               0.468    0.043    0.390    0.558    1.000 gamma(1,.5)[sd]
   .Q53               0.828    0.073    0.696    0.979    1.000 gamma(1,.5)[sd]
   .Q54               0.621    0.055    0.519    0.738    1.000 gamma(1,.5)[sd]
   .Q55               0.817    0.074    0.683    0.973    1.000 gamma(1,.5)[sd]
   .Q56               0.553    0.053    0.457    0.666    1.000 gamma(1,.5)[sd]
   .Q57               0.702    0.065    0.582    0.839    1.000 gamma(1,.5)[sd]
   .Q58               0.521    0.047    0.435    0.619    1.000 gamma(1,.5)[sd]
   .Q59               0.372    0.040    0.299    0.456    1.000 gamma(1,.5)[sd]
   .Q60               0.402    0.042    0.327    0.489    1.000 gamma(1,.5)[sd]
   .Q61               0.274    0.027    0.226    0.329    1.000 gamma(1,.5)[sd]
   .Q62               0.157    0.018    0.125    0.194    1.000 gamma(1,.5)[sd]
   .Q63               0.177    0.020    0.141    0.218    1.000 gamma(1,.5)[sd]
   .Q64               0.244    0.024    0.200    0.295    1.000 gamma(1,.5)[sd]
   .Q65               0.244    0.035    0.179    0.315    1.000 gamma(1,.5)[sd]
   .Q66               0.324    0.034    0.261    0.397    1.000 gamma(1,.5)[sd]
   .Q67               0.290    0.034    0.228    0.361    1.000 gamma(1,.5)[sd]
   .Q68               0.586    0.053    0.491    0.697    1.000 gamma(1,.5)[sd]
   .Q69               0.287    0.031    0.231    0.353    1.000 gamma(1,.5)[sd]
   .Q70               0.392    0.039    0.322    0.472    1.000 gamma(1,.5)[sd]
   .Q71               0.483    0.046    0.400    0.580    1.000 gamma(1,.5)[sd]
   .Q72               0.503    0.048    0.417    0.603    1.000 gamma(1,.5)[sd]
    Conscinc_Emcnl    0.840    0.094    0.671    1.038    1.000 gamma(1,.5)[sd]
    Regulaca_Emcnl    0.805    0.116    0.593    1.050    1.000 gamma(1,.5)[sd]
    Conscienci_Scl    0.733    0.077    0.592    0.894    1.000 gamma(1,.5)[sd]
    Autcntrl_Emcnl    1.088    0.107    0.890    1.312    1.000 gamma(1,.5)[sd]
    Criatvdd_Emcnl    0.686    0.092    0.519    0.879    1.000 gamma(1,.5)[sd]

In [16]:
parameterEstimates(
  fit_bayes_emocional,
  ci = TRUE,
  level = 0.95
)

   lhs                    op rhs                    est
1  Consciencia_Emocional  =~ Q48                    1.0000000
2  Consciencia_Emocional  =~ Q49                    1.0223564
3  Consciencia_Emocional  =~ Q50                    0.9469482
4  Consciencia_Emocional  =~ Q51                    0.9412162
5  Consciencia_Emocional  =~ Q52                    0.9474950
6  Consciencia_Emocional  =~ Q53                    0.9528871
7  Consciencia_Emocional  =~ Q54                    0.8880050
8  Regulacao_Emocional    =~ Q55                    1.0000000
9  Regulacao_Emocional    =~ Q56                    0.9939564
10 Regulacao_Emocional    =~ Q57                    1.0254220
11 Regulacao_Emocional    =~ Q58                    0.8919453
12 Regulacao_Emocional    =~ Q59                    1.0475474
13 Regulacao_Emocional    =~ Q60                    1.0265184
14 Consciencia_Social     =~ Q61                    1.0000000
15 Consciencia_Social     =~ Q62                    0.9660942
16 Consciencia_Social     =~ Q63                    1.0122756
17 Consciencia_Social     =~ Q64                    0.9800008
18 Autocontrole_Emocional =~ Q65                    1.0000000
19 Autocontrole_Emocional =~ Q66                    0.9063954
20 Autocontrole_Emocional =~ Q67                    0.8924627
21 Criatividade_Emocional =~ Q68                    1.0000000
22 Criatividade_Emocional =~ Q69                    1.0583559
23 Criatividade_Emocional =~ Q70                    1.1213331
24 Criatividade_Emocional =~ Q71                    1.0949712
25 Criatividade_Emocional =~ Q72                    1.0782832
26 Q48                    ~~ Q48                    0.3751302
27 Q49                    ~~ Q49                    0.5730386
28 Q50                    ~~ Q50                    0.5255706
29 Q51                    ~~ Q51                    0.4440441
30 Q52                    ~~ Q52                    0.4682311
⋮  ⋮                      ⋮  ⋮                      ⋮
36 Q58                    ~~ Q58                    0.5209833
37 Q59                    ~~ Q59                    0.3719303
38 Q60                    ~~ Q60                    0.4020220
39 Q61                    ~~ Q61                    0.2738382
40 Q62                    ~~ Q62                    0.1566993
41 Q63                    ~~ Q63                    0.1772675
42 Q64                    ~~ Q64                    0.2440006
43 Q65                    ~~ Q65                    0.2435682
44 Q66                    ~~ Q66                    0.3243432
45 Q67                    ~~ Q67                    0.2903595
46 Q68                    ~~ Q68                    0.5857874
47 Q69                    ~~ Q69                    0.2867781
48 Q70                    ~~ Q70                    0.3915746
49 Q71                    ~~ Q71                    0.4829869
50 Q72                    ~~ Q72                    0.5028298
51 Consciencia_Emocional  ~~ Consciencia_Emocional  0.8400000
52 Regulacao_Emocional    ~~ Regulacao_Emocional    0.8053099
53 Consciencia_Social     ~~ Consciencia_Social     0.7332909
54 Autocontrole_Emocional ~~ Autocontrole_Emocional 1.0878041
55 Criatividade_Emocional ~~ Criatividade_Emocional 0.6857935
56 Consciencia_Emocional  ~~ Regulacao_Emocional    0.4835852
57 Consciencia_Emocional  ~~ Consciencia_Social     0.4689153
58 Consciencia_Emocional  ~~ Autocontrole_Emocional 0.5197683
59 Consciencia_Emocional  ~~ Criatividade_Emocional 0.5146377
60 Regulacao_Emocional    ~~ Consciencia_Social     0.4653014
61 Regulacao_Emocional    ~~ Autocontrole_Emocional 0.5318445
62 Regulacao_Emocional    ~~ Criatividade_Emocional 0.4834926
63 Consciencia_Social     ~~ Autocontrole_Emocional 0.6502507
64 Consciencia_Social     ~~ Criatividade_Emocional 0.4983781
65 Autocontrole_Emocional ~~ Criatividade_Emocional 0.5645034

## 8️⃣ INVARIÂNCIA DE MEDIDA

#### 🔹Gênero

In [23]:
fit_bayes_config_gender <- bcfa(
  modelo_emocional,
  data = dados,
  group = "Q1",        # exemplo: gênero
  burnin = 2000,
  sample = 5000,
  n.chains = 4
)

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 1).
Chain 1:
Chain 1: Gradient evaluation took 0.005145 seconds
Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 51.45 seconds.
Chain 1: Adjust your expectations accordingly!
Chain 1:
Chain 1:
Chain 1: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 1: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 1: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 1: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 1: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 1: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 1: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 1: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 1: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 1: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 1: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 1: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 1:
Chain 1:  Elapsed Time: 231.359 seconds (Warm-up)
Chain 1:                459.158 seconds (Sampling)
Chain 1:                690.517 seconds (Total)
Chain 1:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 2).
Chain 2:
Chain 2: Gradient evaluation took 0.004895 seconds
Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 48.95 seconds.
Chain 2: Adjust your expectations accordingly!
Chain 2:
Chain 2:
Chain 2: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 2: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 2: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 2: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 2: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 2: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 2: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 2: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 2: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 2: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 2: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 2: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 2:
Chain 2:  Elapsed Time: 220.906 seconds (Warm-up)
Chain 2:                459.454 seconds (Sampling)
Chain 2:                680.36 seconds (Total)
Chain 2:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 3).
Chain 3:
Chain 3: Gradient evaluation took 0.003142 seconds
Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 31.42 seconds.
Chain 3: Adjust your expectations accordingly!
Chain 3:
Chain 3:
Chain 3: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 3: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 3: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 3: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 3: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 3: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 3: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 3: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 3: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 3: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 3: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 3: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 3:
Chain 3:  Elapsed Time: 226.017 seconds (Warm-up)
Chain 3:                445.214 seconds (Sampling)
Chain 3:                671.231 seconds (Total)
Chain 3:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 4).
Chain 4:
Chain 4: Gradient evaluation took 0.004616 seconds
Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 46.16 seconds.
Chain 4: Adjust your expectations accordingly!
Chain 4:
Chain 4:
Chain 4: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 4: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 4: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 4: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 4: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 4: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 4: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 4: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 4: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 4: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 4: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 4: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 4:
Chain 4:  Elapsed Time: 232.776 seconds (Warm-up)
Chain 4:                466.509 seconds (Sampling)
Chain 4:                699.285 seconds (Total)
Chain 4:
Computing post-estimation metrics (including lvs if requested)...

In [30]:
summary(fit_bayes_config_gender)

blavaan 0.5.10 ended normally after 5000 iterations

  Estimator                                      BAYES
  Optimization method                             MCMC
  Number of model parameters                       170

  Number of observations per group:
    Masculino                                      150
    Feminino                                       173

  Statistic                                 MargLogLik         PPP
  Value                                     -10034.267       0.000

Parameter Estimates:



Group 1 [Masculino]:

Latent Variables:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional =~
    Q48                        1.000
    Q49                        0.969    0.099    0.787    1.175    1.000
    Q50                        0.863    0.099    0.678    1.069    1.000
    Q51                        0.935    0.095    0.763    1.132    1.000
    Q52                        0.893    0.094    0.720    1.087    1.000
    Q53                        0.966    0.110    0.761    1.194    1.000
    Q54                        0.860    0.099    0.673    1.063    1.000
  Regulacao_Emocional =~
    Q55                        1.000
    Q56                        0.988    0.102    0.805    1.205    1.000
    Q57                        0.954    0.105    0.764    1.176    1.000
    Q58                        0.795    0.094    0.627    0.997    1.000
    Q59                        0.886    0.094    0.718    1.089    1.000
    Q60                        0.903    0.099    0.727    1.112    1.000
  Consciencia_Social =~
    Q61                        1.000
    Q62                        1.008    0.068    0.884    1.148    1.000
    Q63                        1.035    0.074    0.900    1.187    1.000
    Q64                        0.999    0.078    0.857    1.160    1.000
  Autocontrole_Emocional =~
    Q65                        1.000
    Q66                        0.873    0.063    0.753    1.002    1.000
    Q67                        0.935    0.067    0.808    1.072    1.000
  Criatividade_Emocional =~
    Q68                        1.000
    Q69                        1.103    0.113    0.906    1.348    1.000
    Q70                        1.188    0.132    0.956    1.473    1.000
    Q71                        1.179    0.129    0.953    1.455    1.000
    Q72                        1.225    0.136    0.984    1.517    1.000
    Prior


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)

Covariances:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional ~~
    Regulaca_Emcnl             0.524    0.104    0.344    0.749    1.000
    Conscienci_Scl             0.464    0.085    0.315    0.648    1.000
    Autcntrl_Emcnl             0.555    0.104    0.369    0.779    1.000
    Criatvdd_Emcnl             0.479    0.088    0.327    0.667    1.000
  Regulacao_Emocional ~~
    Conscienci_Scl             0.535    0.097    0.365    0.747    1.001
    Autcntrl_Emcnl             0.699    0.122    0.485    0.967    1.000
    Criatvdd_Emcnl             0.594    0.107    0.409    0.828    1.000
  Consciencia_Social ~~
    Autcntrl_Emcnl             0.693    0.105    0.507    0.921    1.000
    Criatvdd_Emcnl             0.531    0.089    0.375    0.725    1.000
  Autocontrole_Emocional ~~
    Criatvdd_Emcnl             0.550    0.099    0.377    0.766    1.000
    Prior

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)

Intercepts:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               3.858    0.089    3.684    4.034    1.002    normal(0,32)
   .Q49               3.605    0.095    3.418    3.790    1.001    normal(0,32)
   .Q50               3.665    0.094    3.480    3.850    1.001    normal(0,32)
   .Q51               3.998    0.092    3.818    4.181    1.001    normal(0,32)
   .Q52               3.878    0.091    3.696    4.057    1.001    normal(0,32)
   .Q53               3.645    0.104    3.440    3.849    1.001    normal(0,32)
   .Q54               3.965    0.092    3.782    4.143    1.001    normal(0,32)
   .Q55               3.459    0.107    3.247    3.666    1.001    normal(0,32)
   .Q56               3.799    0.100    3.602    3.996    1.001    normal(0,32)
   .Q57               3.485    0.102    3.285    3.686    1.001    normal(0,32)
   .Q58               4.146    0.088    3.976    4.320    1.001    normal(0,32)
   .Q59               3.879    0.087    3.709    4.050    1.001    normal(0,32)
   .Q60               3.912    0.091    3.731    4.092    1.001    normal(0,32)
   .Q61               4.266    0.082    4.104    4.427    1.001    normal(0,32)
   .Q62               4.373    0.077    4.224    4.525    1.001    normal(0,32)
   .Q63               4.419    0.082    4.261    4.581    1.001    normal(0,32)
   .Q64               4.266    0.082    4.107    4.428    1.001    normal(0,32)
   .Q65               4.040    0.097    3.850    4.229    1.001    normal(0,32)
   .Q66               3.926    0.090    3.751    4.101    1.001    normal(0,32)
   .Q67               4.039    0.094    3.858    4.223    1.001    normal(0,32)
   .Q68               3.912    0.090    3.738    4.092    1.001    normal(0,32)
   .Q69               3.966    0.084    3.803    4.134    1.001    normal(0,32)
   .Q70               3.779    0.095    3.595    3.965    1.001    normal(0,32)
   .Q71               3.759    0.092    3.577    3.939    1.001    normal(0,32)
   .Q72               3.746    0.097    3.555    3.936    1.001    normal(0,32)
    Conscinc_Emcnl    0.000
    Regulaca_Emcnl    0.000
    Conscienci_Scl    0.000
    Autcntrl_Emcnl    0.000
    Criatvdd_Emcnl    0.000

Variances:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               0.396    0.063    0.286    0.533    1.000 gamma(1,.5)[sd]
   .Q49               0.610    0.084    0.464    0.794    1.000 gamma(1,.5)[sd]
   .Q50               0.747    0.098    0.579    0.962    1.000 gamma(1,.5)[sd]
   .Q51               0.571    0.079    0.432    0.741    1.000 gamma(1,.5)[sd]
   .Q52               0.622    0.083    0.476    0.802    1.000 gamma(1,.5)[sd]
   .Q53               0.893    0.119    0.686    1.147    1.000 gamma(1,.5)[sd]
   .Q54               0.677    0.091    0.520    0.879    1.000 gamma(1,.5)[sd]
   .Q55               0.764    0.108    0.574    0.999    1.000 gamma(1,.5)[sd]
   .Q56               0.602    0.087    0.452    0.790    1.000 gamma(1,.5)[sd]
   .Q57               0.706    0.097    0.536    0.915    1.000 gamma(1,.5)[sd]
   .Q58               0.541    0.073    0.413    0.702    1.000 gamma(1,.5)[sd]
   .Q59               0.381    0.058    0.280    0.507    1.000 gamma(1,.5)[sd]
   .Q60               0.462    0.067    0.344    0.609    1.000 gamma(1,.5)[sd]
   .Q61               0.285    0.041    0.214    0.373    1.000 gamma(1,.5)[sd]
   .Q62               0.153    0.027    0.105    0.212    1.000 gamma(1,.5)[sd]
   .Q63               0.231    0.035    0.170    0.307    1.000 gamma(1,.5)[sd]
   .Q64               0.293    0.042    0.221    0.384    1.000 gamma(1,.5)[sd]
   .Q65               0.282    0.059    0.176    0.406    1.000 gamma(1,.5)[sd]
   .Q66               0.365    0.056    0.268    0.490    1.000 gamma(1,.5)[sd]
   .Q67               0.325    0.059    0.220    0.453    1.000 gamma(1,.5)[sd]
   .Q68               0.600    0.080    0.462    0.773    1.000 gamma(1,.5)[sd]
   .Q69               0.320    0.048    0.236    0.425    1.000 gamma(1,.5)[sd]
   .Q70               0.503    0.071    0.378    0.656    1.000 gamma(1,.5)[sd]
   .Q71               0.459    0.066    0.345    0.603    1.000 gamma(1,.5)[sd]
   .Q72               0.518    0.074    0.390    0.676    1.000 gamma(1,.5)[sd]
    Conscinc_Emcnl    0.839    0.141    0.587    1.142    1.000 gamma(1,.5)[sd]
    Regulaca_Emcnl    0.976    0.191    0.641    1.387    1.000 gamma(1,.5)[sd]
    Conscienci_Scl    0.732    0.113    0.534    0.978    1.000 gamma(1,.5)[sd]
    Autcntrl_Emcnl    1.155    0.166    0.861    1.511    1.000 gamma(1,.5)[sd]
    Criatvdd_Emcnl    0.625    0.127    0.405    0.897    1.000 gamma(1,.5)[sd]


Group 2 [Feminino]:

Latent Variables:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional =~
    Q48                        1.000
    Q49                        1.074    0.097    0.893    1.276    1.000
    Q50                        1.055    0.085    0.900    1.233    1.000
    Q51                        1.005    0.084    0.852    1.179    1.000
    Q52                        1.058    0.086    0.901    1.238    1.001
    Q53                        0.963    0.103    0.768    1.174    1.000
    Q54                        0.940    0.093    0.768    1.132    1.000
  Regulacao_Emocional =~
    Q55                        1.000
    Q56                        1.091    0.136    0.857    1.386    1.000
    Q57                        1.202    0.153    0.937    1.537    1.000
    Q58                        1.083    0.141    0.841    1.391    1.000
    Q59                        1.343    0.162    1.071    1.705    1.000
    Q60                        1.264    0.153    1.002    1.601    1.000
  Consciencia_Social =~
    Q61                        1.000
    Q62                        0.924    0.061    0.811    1.049    1.000
    Q63                        1.016    0.063    0.899    1.146    1.000
    Q64                        0.984    0.067    0.860    1.122    1.000
  Autocontrole_Emocional =~
    Q65                        1.000
    Q66                        0.948    0.061    0.833    1.073    1.000
    Q67                        0.853    0.059    0.743    0.973    1.000
  Criatividade_Emocional =~
    Q68                        1.000
    Q69                        1.012    0.087    0.855    1.199    1.000
    Q70                        1.016    0.092    0.852    1.214    1.000
    Q71                        0.997    0.099    0.816    1.207    1.000
    Q72                        0.889    0.092    0.722    1.085    1.000
    Prior


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)

Covariances:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional ~~
    Regulaca_Emcnl             0.366    0.074    0.238    0.526    1.000
    Conscienci_Scl             0.398    0.071    0.271    0.550    1.000
    Autcntrl_Emcnl             0.398    0.079    0.256    0.565    1.000
    Criatvdd_Emcnl             0.486    0.083    0.341    0.666    1.000
  Regulacao_Emocional ~~
    Conscienci_Scl             0.347    0.069    0.224    0.497    1.000
    Autcntrl_Emcnl             0.333    0.075    0.200    0.492    1.000
    Criatvdd_Emcnl             0.341    0.073    0.214    0.497    1.000
  Consciencia_Social ~~
    Autcntrl_Emcnl             0.558    0.084    0.409    0.737    1.000
    Criatvdd_Emcnl             0.437    0.075    0.304    0.599    1.000
  Autocontrole_Emocional ~~
    Criatvdd_Emcnl             0.527    0.089    0.370    0.720    1.000
    Prior

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)

Intercepts:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               4.267    0.079    4.113    4.421    1.000    normal(0,32)
   .Q49               4.099    0.089    3.924    4.273    1.000    normal(0,32)
   .Q50               4.117    0.080    3.961    4.272    1.000    normal(0,32)
   .Q51               4.324    0.077    4.175    4.476    1.000    normal(0,32)
   .Q52               4.209    0.080    4.055    4.366    1.000    normal(0,32)
   .Q53               4.123    0.090    3.945    4.301    1.000    normal(0,32)
   .Q54               4.336    0.083    4.173    4.499    1.000    normal(0,32)
   .Q55               3.803    0.091    3.623    3.980    1.000    normal(0,32)
   .Q56               3.977    0.082    3.816    4.138    1.000    normal(0,32)
   .Q57               3.533    0.094    3.345    3.716    1.000    normal(0,32)
   .Q58               4.214    0.082    4.054    4.376    1.000    normal(0,32)
   .Q59               3.937    0.088    3.766    4.109    1.000    normal(0,32)
   .Q60               4.070    0.085    3.902    4.237    1.000    normal(0,32)
   .Q61               4.399    0.075    4.252    4.546    1.000    normal(0,32)
   .Q62               4.549    0.067    4.418    4.681    1.000    normal(0,32)
   .Q63               4.526    0.070    4.390    4.663    1.000    normal(0,32)
   .Q64               4.445    0.071    4.305    4.585    1.000    normal(0,32)
   .Q65               4.347    0.084    4.184    4.511    1.000    normal(0,32)
   .Q66               4.185    0.082    4.024    4.345    1.000    normal(0,32)
   .Q67               4.359    0.075    4.212    4.507    1.000    normal(0,32)
   .Q68               3.953    0.087    3.783    4.123    1.000    normal(0,32)
   .Q69               4.207    0.076    4.058    4.358    1.000    normal(0,32)
   .Q70               4.156    0.079    4.002    4.311    1.000    normal(0,32)
   .Q71               4.000    0.086    3.829    4.166    1.000    normal(0,32)
   .Q72               4.156    0.080    4.001    4.312    1.000    normal(0,32)
    Conscinc_Emcnl    0.000
    Regulaca_Emcnl    0.000
    Conscienci_Scl    0.000
    Autcntrl_Emcnl    0.000
    Criatvdd_Emcnl    0.000

Variances:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               0.391    0.051    0.301    0.498    1.000 gamma(1,.5)[sd]
   .Q49               0.585    0.072    0.459    0.738    1.000 gamma(1,.5)[sd]
   .Q50               0.333    0.044    0.254    0.427    1.000 gamma(1,.5)[sd]
   .Q51               0.338    0.045    0.260    0.434    1.000 gamma(1,.5)[sd]
   .Q52               0.332    0.045    0.252    0.429    1.000 gamma(1,.5)[sd]
   .Q53               0.783    0.091    0.622    0.977    1.000 gamma(1,.5)[sd]
   .Q54               0.600    0.072    0.473    0.757    1.000 gamma(1,.5)[sd]
   .Q55               0.868    0.104    0.687    1.093    1.000 gamma(1,.5)[sd]
   .Q56               0.509    0.066    0.392    0.650    1.000 gamma(1,.5)[sd]
   .Q57               0.724    0.090    0.565    0.918    1.000 gamma(1,.5)[sd]
   .Q58               0.527    0.066    0.411    0.668    1.000 gamma(1,.5)[sd]
   .Q59               0.353    0.055    0.256    0.470    1.000 gamma(1,.5)[sd]
   .Q60               0.357    0.054    0.262    0.473    1.000 gamma(1,.5)[sd]
   .Q61               0.279    0.038    0.212    0.363    1.000 gamma(1,.5)[sd]
   .Q62               0.182    0.026    0.136    0.238    1.000 gamma(1,.5)[sd]
   .Q63               0.126    0.022    0.088    0.173    1.000 gamma(1,.5)[sd]
   .Q64               0.194    0.028    0.144    0.255    1.000 gamma(1,.5)[sd]
   .Q65               0.223    0.044    0.144    0.316    1.000 gamma(1,.5)[sd]
   .Q66               0.304    0.046    0.221    0.403    1.000 gamma(1,.5)[sd]
   .Q67               0.260    0.041    0.185    0.350    1.000 gamma(1,.5)[sd]
   .Q68               0.546    0.070    0.423    0.698    1.000 gamma(1,.5)[sd]
   .Q69               0.248    0.038    0.180    0.331    1.000 gamma(1,.5)[sd]
   .Q70               0.313    0.045    0.235    0.409    1.000 gamma(1,.5)[sd]
   .Q71               0.528    0.067    0.411    0.672    1.000 gamma(1,.5)[sd]
   .Q72               0.512    0.064    0.398    0.647    1.000 gamma(1,.5)[sd]
    Conscinc_Emcnl    0.725    0.117    0.519    0.976    1.001 gamma(1,.5)[sd]
    Regulaca_Emcnl    0.578    0.132    0.348    0.867    1.000 gamma(1,.5)[sd]
    Conscienci_Scl    0.710    0.103    0.527    0.932    1.000 gamma(1,.5)[sd]
    Autcntrl_Emcnl    0.978    0.131    0.745    1.257    1.000 gamma(1,.5)[sd]
    Criatvdd_Emcnl    0.760    0.133    0.527    1.043    1.000 gamma(1,.5)[sd]

In [24]:
fit_bayes_metric_gender <- bcfa(
  modelo_emocional,
  data = dados,
  group = "Q1",
  group.equal = "loadings",
  burnin = 2000,
  sample = 5000,
  n.chains = 4
)

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 1).
Chain 1:
Chain 1: Gradient evaluation took 0.003631 seconds
Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 36.31 seconds.
Chain 1: Adjust your expectations accordingly!
Chain 1:
Chain 1:
Chain 1: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 1: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 1: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 1: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 1: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 1: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 1: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 1: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 1: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 1: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 1: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 1: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 1:
Chain 1:  Elapsed Time: 189.923 seconds (Warm-up)
Chain 1:                424.82 seconds (Sampling)
Chain 1:                614.743 seconds (Total)
Chain 1:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 2).
Chain 2:
Chain 2: Gradient evaluation took 0.003479 seconds
Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 34.79 seconds.
Chain 2: Adjust your expectations accordingly!
Chain 2:
Chain 2:
Chain 2: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 2: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 2: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 2: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 2: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 2: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 2: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 2: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 2: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 2: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 2: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 2: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 2:
Chain 2:  Elapsed Time: 190.405 seconds (Warm-up)
Chain 2:                402.273 seconds (Sampling)
Chain 2:                592.678 seconds (Total)
Chain 2:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 3).
Chain 3:
Chain 3: Gradient evaluation took 0.003732 seconds
Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 37.32 seconds.
Chain 3: Adjust your expectations accordingly!
Chain 3:
Chain 3:
Chain 3: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 3: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 3: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 3: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 3: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 3: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 3: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 3: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 3: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 3: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 3: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 3: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 3:
Chain 3:  Elapsed Time: 186.703 seconds (Warm-up)
Chain 3:                387.731 seconds (Sampling)
Chain 3:                574.434 seconds (Total)
Chain 3:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 4).
Chain 4:
Chain 4: Gradient evaluation took 0.004198 seconds
Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 41.98 seconds.
Chain 4: Adjust your expectations accordingly!
Chain 4:
Chain 4:
Chain 4: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 4: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 4: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 4: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 4: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 4: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 4: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 4: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 4: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 4: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 4: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 4: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 4:
Chain 4:  Elapsed Time: 190.421 seconds (Warm-up)
Chain 4:                423.412 seconds (Sampling)
Chain 4:                613.833 seconds (Total)
Chain 4:
Computing post-estimation metrics (including lvs if requested)...

In [31]:
summary(fit_bayes_metric_gender)

blavaan 0.5.10 ended normally after 5000 iterations

  Estimator                                      BAYES
  Optimization method                             MCMC
  Number of model parameters                       170
  Number of equality constraints                    20

  Number of observations per group:
    Masculino                                      150
    Feminino                                       173

  Statistic                                 MargLogLik         PPP
  Value                                      -9954.450       0.000

Parameter Estimates:



Group 1 [Masculino]:

Latent Variables:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional =~
    Q48                        1.000
    Q49     (.p2.)             1.013    0.066    0.887    1.148    1.000
    Q50     (.p3.)             0.968    0.060    0.855    1.091    1.000
    Q51     (.p4.)             0.957    0.060    0.845    1.078    1.000
    Q52     (.p5.)             0.976    0.060    0.863    1.097    1.000
    Q53     (.p6.)             0.946    0.072    0.810    1.091    1.000
    Q54     (.p7.)             0.891    0.065    0.768    1.022    1.000
  Regulacao_Emocional =~
    Q55                        1.000
    Q56     (.p9.)             0.995    0.079    0.851    1.160    1.000
    Q57     (.10.)             1.040    0.085    0.887    1.219    1.000
    Q58     (.11.)             0.904    0.077    0.762    1.065    1.000
    Q59     (.12.)             1.063    0.082    0.915    1.237    1.000
    Q60     (.13.)             1.041    0.081    0.893    1.215    1.000
  Consciencia_Social =~
    Q61                        1.000
    Q62     (.15.)             0.958    0.044    0.875    1.050    1.000
    Q63     (.16.)             1.018    0.047    0.931    1.114    1.000
    Q64     (.17.)             0.983    0.049    0.889    1.085    1.000
  Autocontrole_Emocional =~
    Q65                        1.000
    Q66     (.19.)             0.907    0.043    0.825    0.994    1.000
    Q67     (.20.)             0.885    0.044    0.802    0.973    1.000
  Criatividade_Emocional =~
    Q68                        1.000
    Q69     (.22.)             1.034    0.066    0.911    1.171    1.000
    Q70     (.23.)             1.067    0.072    0.934    1.215    1.000
    Q71     (.24.)             1.055    0.076    0.915    1.212    1.000
    Q72     (.25.)             1.011    0.075    0.871    1.166    1.000
    Prior


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)

Covariances:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional ~~
    Regulaca_Emcnl             0.451    0.085    0.301    0.632    1.001
    Conscienci_Scl             0.459    0.080    0.319    0.633    1.001
    Autcntrl_Emcnl             0.531    0.097    0.359    0.737    1.001
    Criatvdd_Emcnl             0.503    0.085    0.355    0.685    1.001
  Regulacao_Emocional ~~
    Conscienci_Scl             0.492    0.086    0.341    0.677    1.001
    Autcntrl_Emcnl             0.627    0.107    0.441    0.855    1.000
    Criatvdd_Emcnl             0.586    0.095    0.419    0.791    1.000
  Consciencia_Social ~~
    Autcntrl_Emcnl             0.715    0.104    0.533    0.938    1.000
    Criatvdd_Emcnl             0.602    0.089    0.447    0.792    1.001
  Autocontrole_Emocional ~~
    Criatvdd_Emcnl             0.606    0.101    0.428    0.821    1.000
    Prior

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)

Intercepts:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               3.859    0.090    3.681    4.035    1.001    normal(0,32)
   .Q49               3.606    0.097    3.415    3.796    1.001    normal(0,32)
   .Q50               3.665    0.100    3.470    3.860    1.001    normal(0,32)
   .Q51               3.999    0.093    3.815    4.179    1.000    normal(0,32)
   .Q52               3.879    0.096    3.692    4.066    1.001    normal(0,32)
   .Q53               3.646    0.104    3.442    3.852    1.000    normal(0,32)
   .Q54               3.966    0.093    3.784    4.148    1.001    normal(0,32)
   .Q55               3.458    0.104    3.254    3.659    1.000    normal(0,32)
   .Q56               3.799    0.098    3.607    3.989    1.000    normal(0,32)
   .Q57               3.486    0.103    3.283    3.684    1.001    normal(0,32)
   .Q58               4.146    0.089    3.970    4.321    1.000    normal(0,32)
   .Q59               3.878    0.091    3.703    4.056    1.001    normal(0,32)
   .Q60               3.911    0.093    3.727    4.094    1.000    normal(0,32)
   .Q61               4.265    0.084    4.100    4.433    1.001    normal(0,32)
   .Q62               4.372    0.076    4.223    4.521    1.001    normal(0,32)
   .Q63               4.419    0.083    4.254    4.581    1.002    normal(0,32)
   .Q64               4.265    0.084    4.099    4.429    1.001    normal(0,32)
   .Q65               4.038    0.098    3.844    4.230    1.001    normal(0,32)
   .Q66               3.925    0.094    3.740    4.108    1.001    normal(0,32)
   .Q67               4.038    0.092    3.855    4.218    1.001    normal(0,32)
   .Q68               3.912    0.095    3.726    4.098    1.001    normal(0,32)
   .Q69               3.966    0.086    3.798    4.134    1.001    normal(0,32)
   .Q70               3.779    0.096    3.589    3.968    1.001    normal(0,32)
   .Q71               3.759    0.094    3.576    3.944    1.001    normal(0,32)
   .Q72               3.745    0.095    3.560    3.931    1.001    normal(0,32)
    Conscinc_Emcnl    0.000
    Regulaca_Emcnl    0.000
    Conscienci_Scl    0.000
    Autcntrl_Emcnl    0.000
    Criatvdd_Emcnl    0.000

Variances:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               0.406    0.061    0.299    0.538    1.000 gamma(1,.5)[sd]
   .Q49               0.601    0.083    0.456    0.781    1.000 gamma(1,.5)[sd]
   .Q50               0.733    0.095    0.569    0.939    1.000 gamma(1,.5)[sd]
   .Q51               0.564    0.077    0.430    0.731    1.000 gamma(1,.5)[sd]
   .Q52               0.612    0.081    0.470    0.790    1.000 gamma(1,.5)[sd]
   .Q53               0.907    0.117    0.703    1.157    1.000 gamma(1,.5)[sd]
   .Q54               0.679    0.089    0.525    0.874    1.000 gamma(1,.5)[sd]
   .Q55               0.822    0.110    0.629    1.060    1.000 gamma(1,.5)[sd]
   .Q56               0.656    0.091    0.498    0.853    1.000 gamma(1,.5)[sd]
   .Q57               0.736    0.100    0.562    0.951    1.000 gamma(1,.5)[sd]
   .Q58               0.521    0.069    0.401    0.672    1.000 gamma(1,.5)[sd]
   .Q59               0.349    0.054    0.254    0.467    1.000 gamma(1,.5)[sd]
   .Q60               0.432    0.062    0.324    0.567    1.000 gamma(1,.5)[sd]
   .Q61               0.281    0.040    0.212    0.368    1.000 gamma(1,.5)[sd]
   .Q62               0.157    0.027    0.110    0.215    1.000 gamma(1,.5)[sd]
   .Q63               0.229    0.035    0.168    0.304    1.000 gamma(1,.5)[sd]
   .Q64               0.293    0.041    0.221    0.383    1.000 gamma(1,.5)[sd]
   .Q65               0.270    0.054    0.172    0.387    1.000 gamma(1,.5)[sd]
   .Q66               0.355    0.055    0.258    0.472    1.000 gamma(1,.5)[sd]
   .Q67               0.343    0.056    0.243    0.464    1.000 gamma(1,.5)[sd]
   .Q68               0.578    0.077    0.446    0.747    1.000 gamma(1,.5)[sd]
   .Q69               0.307    0.047    0.225    0.410    1.000 gamma(1,.5)[sd]
   .Q70               0.511    0.070    0.389    0.662    1.000 gamma(1,.5)[sd]
   .Q71               0.470    0.066    0.354    0.616    1.000 gamma(1,.5)[sd]
   .Q72               0.553    0.076    0.421    0.715    1.000 gamma(1,.5)[sd]
    Conscinc_Emcnl    0.780    0.115    0.578    1.031    1.000 gamma(1,.5)[sd]
    Regulaca_Emcnl    0.787    0.139    0.544    1.085    1.000 gamma(1,.5)[sd]
    Conscienci_Scl    0.768    0.106    0.581    0.996    1.000 gamma(1,.5)[sd]
    Autcntrl_Emcnl    1.171    0.156    0.899    1.512    1.000 gamma(1,.5)[sd]
    Criatvdd_Emcnl    0.748    0.118    0.543    1.004    1.001 gamma(1,.5)[sd]


Group 2 [Feminino]:

Latent Variables:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional =~
    Q48                        1.000
    Q49     (.p2.)             1.013    0.066    0.887    1.148    1.000
    Q50     (.p3.)             0.968    0.060    0.855    1.091    1.000
    Q51     (.p4.)             0.957    0.060    0.845    1.078    1.000
    Q52     (.p5.)             0.976    0.060    0.863    1.097    1.000
    Q53     (.p6.)             0.946    0.072    0.810    1.091    1.000
    Q54     (.p7.)             0.891    0.065    0.768    1.022    1.000
  Regulacao_Emocional =~
    Q55                        1.000
    Q56     (.p9.)             0.995    0.079    0.851    1.160    1.000
    Q57     (.10.)             1.040    0.085    0.887    1.219    1.000
    Q58     (.11.)             0.904    0.077    0.762    1.065    1.000
    Q59     (.12.)             1.063    0.082    0.915    1.237    1.000
    Q60     (.13.)             1.041    0.081    0.893    1.215    1.000
  Consciencia_Social =~
    Q61                        1.000
    Q62     (.15.)             0.958    0.044    0.875    1.050    1.000
    Q63     (.16.)             1.018    0.047    0.931    1.114    1.000
    Q64     (.17.)             0.983    0.049    0.889    1.085    1.000
  Autocontrole_Emocional =~
    Q65                        1.000
    Q66     (.19.)             0.907    0.043    0.825    0.994    1.000
    Q67     (.20.)             0.885    0.044    0.802    0.973    1.000
  Criatividade_Emocional =~
    Q68                        1.000
    Q69     (.22.)             1.034    0.066    0.911    1.171    1.000
    Q70     (.23.)             1.067    0.072    0.934    1.215    1.000
    Q71     (.24.)             1.055    0.076    0.915    1.212    1.000
    Q72     (.25.)             1.011    0.075    0.871    1.166    1.000
    Prior































Covariances:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional ~~
    Regulaca_Emcnl             0.455    0.080    0.315    0.627    1.000
    Conscienci_Scl             0.417    0.070    0.293    0.568    1.000
    Autcntrl_Emcnl             0.424    0.081    0.278    0.595    1.000
    Criatvdd_Emcnl             0.488    0.077    0.353    0.654    1.000
  Regulacao_Emocional ~~
    Conscienci_Scl             0.405    0.072    0.276    0.560    1.000
    Autcntrl_Emcnl             0.393    0.082    0.246    0.565    1.000
    Criatvdd_Emcnl             0.382    0.073    0.251    0.540    1.000
  Consciencia_Social ~~
    Autcntrl_Emcnl             0.556    0.081    0.411    0.728    1.000
    Criatvdd_Emcnl             0.413    0.068    0.294    0.562    1.000
  Autocontrole_Emocional ~~
    Criatvdd_Emcnl             0.507    0.083    0.360    0.688    1.000
    Prior

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)

Intercepts:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               4.267    0.083    4.103    4.431    1.001    normal(0,32)
   .Q49               4.099    0.091    3.919    4.277    1.001    normal(0,32)
   .Q50               4.116    0.079    3.961    4.274    1.001    normal(0,32)
   .Q51               4.324    0.079    4.168    4.479    1.001    normal(0,32)
   .Q52               4.209    0.081    4.052    4.367    1.002    normal(0,32)
   .Q53               4.122    0.093    3.941    4.305    1.001    normal(0,32)
   .Q54               4.336    0.085    4.168    4.503    1.001    normal(0,32)
   .Q55               3.804    0.097    3.611    3.995    1.000    normal(0,32)
   .Q56               3.977    0.085    3.810    4.142    1.000    normal(0,32)
   .Q57               3.532    0.095    3.345    3.716    1.000    normal(0,32)
   .Q58               4.214    0.083    4.048    4.376    1.000    normal(0,32)
   .Q59               3.937    0.086    3.768    4.105    1.000    normal(0,32)
   .Q60               4.070    0.084    3.906    4.233    1.000    normal(0,32)
   .Q61               4.400    0.075    4.253    4.548    1.000    normal(0,32)
   .Q62               4.550    0.069    4.415    4.686    1.000    normal(0,32)
   .Q63               4.527    0.070    4.393    4.665    1.000    normal(0,32)
   .Q64               4.446    0.071    4.306    4.584    1.001    normal(0,32)
   .Q65               4.348    0.083    4.185    4.511    1.000    normal(0,32)
   .Q66               4.185    0.080    4.027    4.343    1.001    normal(0,32)
   .Q67               4.359    0.076    4.211    4.510    1.000    normal(0,32)
   .Q68               3.954    0.085    3.786    4.118    1.001    normal(0,32)
   .Q69               4.208    0.076    4.058    4.356    1.001    normal(0,32)
   .Q70               4.157    0.080    3.997    4.310    1.001    normal(0,32)
   .Q71               4.000    0.086    3.829    4.165    1.001    normal(0,32)
   .Q72               4.156    0.084    3.991    4.319    1.001    normal(0,32)
    Conscinc_Emcnl    0.000
    Regulaca_Emcnl    0.000
    Conscienci_Scl    0.000
    Autcntrl_Emcnl    0.000
    Criatvdd_Emcnl    0.000

Variances:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               0.382    0.050    0.293    0.490    1.000 gamma(1,.5)[sd]
   .Q49               0.582    0.070    0.458    0.731    1.000 gamma(1,.5)[sd]
   .Q50               0.340    0.045    0.260    0.436    1.000 gamma(1,.5)[sd]
   .Q51               0.339    0.045    0.261    0.437    1.000 gamma(1,.5)[sd]
   .Q52               0.338    0.045    0.259    0.436    1.000 gamma(1,.5)[sd]
   .Q53               0.776    0.092    0.615    0.979    1.000 gamma(1,.5)[sd]
   .Q54               0.594    0.071    0.468    0.748    1.000 gamma(1,.5)[sd]
   .Q55               0.827    0.101    0.649    1.046    1.000 gamma(1,.5)[sd]
   .Q56               0.483    0.064    0.370    0.621    1.000 gamma(1,.5)[sd]
   .Q57               0.695    0.086    0.542    0.879    1.000 gamma(1,.5)[sd]
   .Q58               0.537    0.067    0.419    0.684    1.000 gamma(1,.5)[sd]
   .Q59               0.390    0.057    0.289    0.512    1.000 gamma(1,.5)[sd]
   .Q60               0.383    0.056    0.284    0.506    1.000 gamma(1,.5)[sd]
   .Q61               0.277    0.037    0.213    0.358    1.000 gamma(1,.5)[sd]
   .Q62               0.179    0.026    0.133    0.235    1.000 gamma(1,.5)[sd]
   .Q63               0.128    0.022    0.089    0.174    1.000 gamma(1,.5)[sd]
   .Q64               0.196    0.028    0.146    0.258    1.000 gamma(1,.5)[sd]
   .Q65               0.228    0.043    0.150    0.320    1.000 gamma(1,.5)[sd]
   .Q66               0.316    0.046    0.235    0.414    1.000 gamma(1,.5)[sd]
   .Q67               0.250    0.041    0.179    0.336    1.000 gamma(1,.5)[sd]
   .Q68               0.553    0.069    0.432    0.701    1.000 gamma(1,.5)[sd]
   .Q69               0.255    0.038    0.188    0.336    1.000 gamma(1,.5)[sd]
   .Q70               0.312    0.045    0.233    0.409    1.000 gamma(1,.5)[sd]
   .Q71               0.521    0.066    0.404    0.663    1.000 gamma(1,.5)[sd]
   .Q72               0.503    0.062    0.393    0.636    1.000 gamma(1,.5)[sd]
    Conscinc_Emcnl    0.804    0.110    0.610    1.042    1.000 gamma(1,.5)[sd]
    Regulaca_Emcnl    0.784    0.131    0.557    1.070    1.000 gamma(1,.5)[sd]
    Conscienci_Scl    0.696    0.092    0.534    0.895    1.000 gamma(1,.5)[sd]
    Autcntrl_Emcnl    0.978    0.126    0.755    1.247    1.000 gamma(1,.5)[sd]
    Criatvdd_Emcnl    0.690    0.107    0.501    0.922    1.000 gamma(1,.5)[sd]

In [21]:
fit_bayes_gender <- bcfa(
  modelo_emocional,
  data = dados,
  group = "Q1",
  burnin = 2000,
  sample = 5000,
  n.chains = 4,
  group.equal = c("loadings", "intercepts")
)

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 1).
Chain 1:
Chain 1: Gradient evaluation took 0.003727 seconds
Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 37.27 seconds.
Chain 1: Adjust your expectations accordingly!
Chain 1:
Chain 1:
Chain 1: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 1: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 1: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 1: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 1: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 1: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 1: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 1: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 1: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 1: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 1: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 1: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 1:
Chain 1:  Elapsed Time: 190.325 seconds (Warm-up)
Chain 1:                555.155 seconds (Sampling)
Chain 1:                745.48 seconds (Total)
Chain 1:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 2).
Chain 2:
Chain 2: Gradient evaluation took 0.00313 seconds
Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 31.3 seconds.
Chain 2: Adjust your expectations accordingly!
Chain 2:
Chain 2:
Chain 2: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 2: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 2: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 2: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 2: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 2: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 2: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 2: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 2: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 2: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 2: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 2: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 2:
Chain 2:  Elapsed Time: 200.042 seconds (Warm-up)
Chain 2:                547.652 seconds (Sampling)
Chain 2:                747.694 seconds (Total)
Chain 2:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 3).
Chain 3:
Chain 3: Gradient evaluation took 0.00308 seconds
Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 30.8 seconds.
Chain 3: Adjust your expectations accordingly!
Chain 3:
Chain 3:
Chain 3: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 3: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 3: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 3: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 3: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 3: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 3: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 3: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 3: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 3: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 3: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 3: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 3:
Chain 3:  Elapsed Time: 197.149 seconds (Warm-up)
Chain 3:                399.443 seconds (Sampling)
Chain 3:                596.592 seconds (Total)
Chain 3:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 4).
Chain 4:
Chain 4: Gradient evaluation took 0.004904 seconds
Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 49.04 seconds.
Chain 4: Adjust your expectations accordingly!
Chain 4:
Chain 4:
Chain 4: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 4: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 4: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 4: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 4: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 4: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 4: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 4: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 4: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 4: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 4: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 4: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 4:
Chain 4:  Elapsed Time: 197.649 seconds (Warm-up)
Chain 4:                707.967 seconds (Sampling)
Chain 4:                905.616 seconds (Total)
Chain 4:
Computing post-estimation metrics (including lvs if requested)...

In [29]:
summary(fit_bayes_gender)

blavaan 0.5.10 ended normally after 5000 iterations

  Estimator                                      BAYES
  Optimization method                             MCMC
  Number of model parameters                       175
  Number of equality constraints                    45

  Number of observations per group:
    Masculino                                      150
    Feminino                                       173

  Statistic                                 MargLogLik         PPP
  Value                                      -9843.593       0.000

Parameter Estimates:



Group 1 [Masculino]:

Latent Variables:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional =~
    Q48                        1.000
    Q49     (.p2.)             1.022    0.065    0.899    1.154    1.000
    Q50     (.p3.)             0.972    0.059    0.861    1.096    1.000
    Q51     (.p4.)             0.947    0.057    0.837    1.063    1.000
    Q52     (.p5.)             0.965    0.058    0.856    1.083    1.000
    Q53     (.p6.)             0.956    0.070    0.823    1.098    1.000
    Q54     (.p7.)             0.890    0.063    0.771    1.019    1.000
  Regulacao_Emocional =~
    Q55                        1.000
    Q56     (.p9.)             0.985    0.077    0.842    1.147    1.000
    Q57     (.10.)             1.025    0.083    0.872    1.196    1.000
    Q58     (.11.)             0.891    0.075    0.754    1.050    1.000
    Q59     (.12.)             1.046    0.080    0.900    1.215    1.000
    Q60     (.13.)             1.029    0.080    0.883    1.197    1.000
  Consciencia_Social =~
    Q61                        1.000
    Q62     (.15.)             0.959    0.045    0.874    1.049    1.000
    Q63     (.16.)             1.015    0.047    0.927    1.111    1.000
    Q64     (.17.)             0.984    0.050    0.890    1.087    1.000
  Autocontrole_Emocional =~
    Q65                        1.000
    Q66     (.19.)             0.904    0.043    0.824    0.990    1.000
    Q67     (.20.)             0.888    0.044    0.805    0.978    1.000
  Criatividade_Emocional =~
    Q68                        1.000
    Q69     (.22.)             1.054    0.068    0.929    1.196    1.000
    Q70     (.23.)             1.100    0.076    0.961    1.259    1.000
    Q71     (.24.)             1.076    0.077    0.936    1.236    1.000
    Q72     (.25.)             1.048    0.077    0.906    1.209    1.000
    Prior


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)

Covariances:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional ~~
    Regulaca_Emcnl             0.456    0.086    0.305    0.643    1.000
    Conscienci_Scl             0.458    0.079    0.317    0.629    1.000
    Autcntrl_Emcnl             0.531    0.097    0.357    0.737    1.000
    Criatvdd_Emcnl             0.492    0.082    0.346    0.670    1.000
  Regulacao_Emocional ~~
    Conscienci_Scl             0.498    0.087    0.347    0.684    1.000
    Autcntrl_Emcnl             0.636    0.109    0.445    0.875    1.000
    Criatvdd_Emcnl             0.581    0.095    0.416    0.783    1.000
  Consciencia_Social ~~
    Autcntrl_Emcnl             0.716    0.105    0.533    0.942    1.000
    Criatvdd_Emcnl             0.589    0.088    0.436    0.778    1.000
  Autocontrole_Emocional ~~
    Criatvdd_Emcnl             0.593    0.100    0.417    0.809    1.000
    Prior

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)

Intercepts:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48     (.66.)    3.858    0.083    3.696    4.020    1.001    normal(0,32)
   .Q49     (.67.)    3.646    0.088    3.474    3.819    1.001    normal(0,32)
   .Q50     (.68.)    3.702    0.084    3.537    3.865    1.001    normal(0,32)
   .Q51     (.69.)    3.957    0.080    3.798    4.116    1.000    normal(0,32)
   .Q52     (.70.)    3.835    0.082    3.671    3.997    1.001    normal(0,32)
   .Q53     (.71.)    3.694    0.089    3.518    3.868    1.000    normal(0,32)
   .Q54     (.72.)    3.969    0.080    3.811    4.127    1.001    normal(0,32)
   .Q55     (.73.)    3.576    0.092    3.393    3.755    1.000    normal(0,32)
   .Q56     (.74.)    3.832    0.085    3.666    3.999    1.001    normal(0,32)
   .Q57     (.75.)    3.441    0.091    3.262    3.617    1.000    normal(0,32)
   .Q58     (.76.)    4.123    0.079    3.967    4.280    1.000    normal(0,32)
   .Q59     (.77.)    3.842    0.086    3.675    4.008    1.001    normal(0,32)
   .Q60     (.78.)    3.929    0.085    3.761    4.094    1.001    normal(0,32)
   .Q61     (.79.)    4.258    0.078    4.106    4.412    1.001    normal(0,32)
   .Q62     (.80.)    4.391    0.073    4.249    4.533    1.001    normal(0,32)
   .Q63     (.81.)    4.391    0.077    4.240    4.542    1.001    normal(0,32)
   .Q64     (.82.)    4.288    0.076    4.138    4.440    1.001    normal(0,32)
   .Q65     (.83.)    4.036    0.094    3.851    4.222    1.001    normal(0,32)
   .Q66     (.84.)    3.913    0.088    3.741    4.082    1.001    normal(0,32)
   .Q67     (.85.)    4.065    0.086    3.897    4.232    1.001    normal(0,32)
   .Q68     (.86.)    3.798    0.083    3.634    3.960    1.001    normal(0,32)
   .Q69     (.87.)    3.953    0.080    3.796    4.108    1.001    normal(0,32)
   .Q70     (.88.)    3.845    0.086    3.674    4.013    1.001    normal(0,32)
   .Q71     (.89.)    3.744    0.085    3.577    3.912    1.001    normal(0,32)
   .Q72     (.90.)    3.828    0.085    3.660    3.995    1.001    normal(0,32)
    Cnscn_E           0.000
    Rglc_Em           0.000
    Cnscn_S           0.000
    Atcnt_E           0.000
    Crtvd_E           0.000

Variances:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               0.405    0.061    0.299    0.537    1.000 gamma(1,.5)[sd]
   .Q49               0.599    0.082    0.457    0.774    1.000 gamma(1,.5)[sd]
   .Q50               0.731    0.096    0.564    0.939    1.000 gamma(1,.5)[sd]
   .Q51               0.567    0.077    0.435    0.736    1.000 gamma(1,.5)[sd]
   .Q52               0.614    0.083    0.471    0.791    1.000 gamma(1,.5)[sd]
   .Q53               0.902    0.116    0.699    1.150    1.000 gamma(1,.5)[sd]
   .Q54               0.676    0.089    0.522    0.871    1.000 gamma(1,.5)[sd]
   .Q55               0.831    0.112    0.634    1.076    1.000 gamma(1,.5)[sd]
   .Q56               0.652    0.090    0.496    0.848    1.000 gamma(1,.5)[sd]
   .Q57               0.735    0.099    0.563    0.948    1.000 gamma(1,.5)[sd]
   .Q58               0.520    0.069    0.399    0.669    1.000 gamma(1,.5)[sd]
   .Q59               0.351    0.055    0.256    0.471    1.000 gamma(1,.5)[sd]
   .Q60               0.431    0.062    0.322    0.566    1.000 gamma(1,.5)[sd]
   .Q61               0.280    0.040    0.210    0.366    1.000 gamma(1,.5)[sd]
   .Q62               0.156    0.027    0.109    0.214    1.000 gamma(1,.5)[sd]
   .Q63               0.230    0.035    0.169    0.304    1.000 gamma(1,.5)[sd]
   .Q64               0.293    0.041    0.220    0.383    1.000 gamma(1,.5)[sd]
   .Q65               0.269    0.054    0.172    0.386    1.000 gamma(1,.5)[sd]
   .Q66               0.354    0.055    0.260    0.474    1.000 gamma(1,.5)[sd]
   .Q67               0.341    0.056    0.243    0.463    1.000 gamma(1,.5)[sd]
   .Q68               0.596    0.080    0.459    0.771    1.000 gamma(1,.5)[sd]
   .Q69               0.307    0.046    0.226    0.407    1.000 gamma(1,.5)[sd]
   .Q70               0.510    0.070    0.387    0.662    1.000 gamma(1,.5)[sd]
   .Q71               0.467    0.065    0.354    0.606    1.000 gamma(1,.5)[sd]
   .Q72               0.552    0.076    0.419    0.717    1.000 gamma(1,.5)[sd]
    Conscinc_Emcnl    0.780    0.114    0.582    1.028    1.000 gamma(1,.5)[sd]
    Regulaca_Emcnl    0.807    0.142    0.563    1.119    1.000 gamma(1,.5)[sd]
    Conscienci_Scl    0.768    0.106    0.584    1.003    1.000 gamma(1,.5)[sd]
    Autcntrl_Emcnl    1.174    0.159    0.897    1.514    1.000 gamma(1,.5)[sd]
    Criatvdd_Emcnl    0.718    0.115    0.517    0.965    1.000 gamma(1,.5)[sd]


Group 2 [Feminino]:

Latent Variables:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional =~
    Q48                        1.000
    Q49     (.p2.)             1.022    0.065    0.899    1.154    1.000
    Q50     (.p3.)             0.972    0.059    0.861    1.096    1.000
    Q51     (.p4.)             0.947    0.057    0.837    1.063    1.000
    Q52     (.p5.)             0.965    0.058    0.856    1.083    1.000
    Q53     (.p6.)             0.956    0.070    0.823    1.098    1.000
    Q54     (.p7.)             0.890    0.063    0.771    1.019    1.000
  Regulacao_Emocional =~
    Q55                        1.000
    Q56     (.p9.)             0.985    0.077    0.842    1.147    1.000
    Q57     (.10.)             1.025    0.083    0.872    1.196    1.000
    Q58     (.11.)             0.891    0.075    0.754    1.050    1.000
    Q59     (.12.)             1.046    0.080    0.900    1.215    1.000
    Q60     (.13.)             1.029    0.080    0.883    1.197    1.000
  Consciencia_Social =~
    Q61                        1.000
    Q62     (.15.)             0.959    0.045    0.874    1.049    1.000
    Q63     (.16.)             1.015    0.047    0.927    1.111    1.000
    Q64     (.17.)             0.984    0.050    0.890    1.087    1.000
  Autocontrole_Emocional =~
    Q65                        1.000
    Q66     (.19.)             0.904    0.043    0.824    0.990    1.000
    Q67     (.20.)             0.888    0.044    0.805    0.978    1.000
  Criatividade_Emocional =~
    Q68                        1.000
    Q69     (.22.)             1.054    0.068    0.929    1.196    1.000
    Q70     (.23.)             1.100    0.076    0.961    1.259    1.000
    Q71     (.24.)             1.076    0.077    0.936    1.236    1.000
    Q72     (.25.)             1.048    0.077    0.906    1.209    1.000
    Prior































Covariances:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional ~~
    Regulaca_Emcnl             0.462    0.082    0.316    0.637    1.000
    Conscienci_Scl             0.418    0.071    0.291    0.570    1.000
    Autcntrl_Emcnl             0.425    0.081    0.279    0.599    1.000
    Criatvdd_Emcnl             0.479    0.077    0.344    0.645    1.000
  Regulacao_Emocional ~~
    Conscienci_Scl             0.411    0.073    0.281    0.568    1.000
    Autcntrl_Emcnl             0.397    0.082    0.250    0.572    1.000
    Criatvdd_Emcnl             0.378    0.073    0.250    0.535    1.000
  Consciencia_Social ~~
    Autcntrl_Emcnl             0.556    0.082    0.410    0.733    1.000
    Criatvdd_Emcnl             0.404    0.067    0.286    0.549    1.000
  Autocontrole_Emocional ~~
    Criatvdd_Emcnl             0.496    0.081    0.353    0.669    1.000
    Prior

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)

Intercepts:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48     (.66.)    3.858    0.083    3.696    4.020    1.001
   .Q49     (.67.)    3.646    0.088    3.474    3.819    1.001
   .Q50     (.68.)    3.702    0.084    3.537    3.865    1.001
   .Q51     (.69.)    3.957    0.080    3.798    4.116    1.000
   .Q52     (.70.)    3.835    0.082    3.671    3.997    1.001
   .Q53     (.71.)    3.694    0.089    3.518    3.868    1.000
   .Q54     (.72.)    3.969    0.080    3.811    4.127    1.001
   .Q55     (.73.)    3.576    0.092    3.393    3.755    1.000
   .Q56     (.74.)    3.832    0.085    3.666    3.999    1.001
   .Q57     (.75.)    3.441    0.091    3.262    3.617    1.000
   .Q58     (.76.)    4.123    0.079    3.967    4.280    1.000
   .Q59     (.77.)    3.842    0.086    3.675    4.008    1.001
   .Q60     (.78.)    3.929    0.085    3.761    4.094    1.001
   .Q61     (.79.)    4.258    0.078    4.106    4.412    1.001
   .Q62     (.80.)    4.391    0.073    4.249    4.533    1.001
   .Q63     (.81.)    4.391    0.077    4.240    4.542    1.001
   .Q64     (.82.)    4.288    0.076    4.138    4.440    1.001
   .Q65     (.83.)    4.036    0.094    3.851    4.222    1.001
   .Q66     (.84.)    3.913    0.088    3.741    4.082    1.001
   .Q67     (.85.)    4.065    0.086    3.897    4.232    1.001
   .Q68     (.86.)    3.798    0.083    3.634    3.960    1.001
   .Q69     (.87.)    3.953    0.080    3.796    4.108    1.001
   .Q70     (.88.)    3.845    0.086    3.674    4.013    1.001
   .Q71     (.89.)    3.744    0.085    3.577    3.912    1.001
   .Q72     (.90.)    3.828    0.085    3.660    3.995    1.001
    Cnscn_E           0.411    0.106    0.202    0.619    1.001    normal(0,10)
    Rglc_Em           0.127    0.106   -0.081    0.333    1.001    normal(0,10)
    Cnscn_S           0.148    0.098   -0.043    0.337    1.001    normal(0,10)
    Atcnt_E           0.314    0.121    0.075    0.552    1.000    normal(0,10)
    Crtvd_E           0.253    0.098    0.060    0.446    1.000    normal(0,10)

Variances:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               0.380    0.049    0.293    0.485    1.000 gamma(1,.5)[sd]
   .Q49               0.580    0.071    0.456    0.734    1.000 gamma(1,.5)[sd]
   .Q50               0.339    0.045    0.259    0.436    1.000 gamma(1,.5)[sd]
   .Q51               0.341    0.044    0.263    0.435    1.000 gamma(1,.5)[sd]
   .Q52               0.341    0.045    0.261    0.438    1.000 gamma(1,.5)[sd]
   .Q53               0.775    0.092    0.613    0.975    1.000 gamma(1,.5)[sd]
   .Q54               0.592    0.071    0.469    0.746    1.000 gamma(1,.5)[sd]
   .Q55               0.836    0.103    0.655    1.056    1.000 gamma(1,.5)[sd]
   .Q56               0.482    0.063    0.371    0.616    1.000 gamma(1,.5)[sd]
   .Q57               0.695    0.088    0.542    0.886    1.000 gamma(1,.5)[sd]
   .Q58               0.537    0.067    0.419    0.681    1.000 gamma(1,.5)[sd]
   .Q59               0.393    0.057    0.291    0.515    1.000 gamma(1,.5)[sd]
   .Q60               0.383    0.055    0.286    0.501    1.000 gamma(1,.5)[sd]
   .Q61               0.276    0.036    0.212    0.356    1.000 gamma(1,.5)[sd]
   .Q62               0.178    0.026    0.133    0.233    1.000 gamma(1,.5)[sd]
   .Q63               0.128    0.022    0.090    0.175    1.000 gamma(1,.5)[sd]
   .Q64               0.196    0.029    0.145    0.257    1.000 gamma(1,.5)[sd]
   .Q65               0.228    0.044    0.149    0.324    1.000 gamma(1,.5)[sd]
   .Q66               0.317    0.046    0.236    0.417    1.000 gamma(1,.5)[sd]
   .Q67               0.249    0.041    0.177    0.336    1.000 gamma(1,.5)[sd]
   .Q68               0.570    0.071    0.445    0.722    1.000 gamma(1,.5)[sd]
   .Q69               0.255    0.038    0.188    0.336    1.000 gamma(1,.5)[sd]
   .Q70               0.310    0.045    0.231    0.407    1.000 gamma(1,.5)[sd]
   .Q71               0.519    0.066    0.403    0.662    1.000 gamma(1,.5)[sd]
   .Q72               0.507    0.064    0.396    0.643    1.000 gamma(1,.5)[sd]
    Conscinc_Emcnl    0.807    0.113    0.606    1.052    1.000 gamma(1,.5)[sd]
    Regulaca_Emcnl    0.803    0.133    0.570    1.090    1.000 gamma(1,.5)[sd]
    Conscienci_Scl    0.697    0.093    0.535    0.897    1.000 gamma(1,.5)[sd]
    Autcntrl_Emcnl    0.977    0.125    0.761    1.248    1.000 gamma(1,.5)[sd]
    Criatvdd_Emcnl    0.661    0.104    0.479    0.883    1.000 gamma(1,.5)[sd]

Foi conduzida uma análise de invariância de medida Bayesiana entre homens (n = 150) e mulheres (n = 173). O modelo configural apresentou adequada representação da estrutura fatorial em ambos os grupos, com cargas fatoriais elevadas e intervalos de credibilidade que não incluíram zero. Em seguida, o modelo métrico, no qual as cargas fatoriais foram igualadas entre os grupos, apresentou melhora no ajuste Bayesiano, conforme indicado pelo aumento do logaritmo da verossimilhança marginal. Por fim, o modelo escalar, com cargas e interceptos restritos à igualdade, manteve estabilidade das estimativas e apresentou o melhor ajuste relativo. Esses resultados fornecem evidência robusta de invariância configural, métrica e escalar do instrumento entre os gêneros, permitindo a comparação válida de médias latentes.

In [36]:
fit_bayes_gender

blavaan 0.5.10 ended normally after 5000 iterations

  Estimator                                      BAYES
  Optimization method                             MCMC
  Number of model parameters                       175
  Number of equality constraints                    45

  Number of observations per group:
    Masculino                                      150
    Feminino                                       173

  Statistic                                 MargLogLik         PPP
  Value                                      -9843.593       0.000

#### 🔹Liderança

In [25]:
fit_bayes_config_leader <- bcfa(
  modelo_emocional,
  data = dados,
  group = "Q4",        
  burnin = 2000,
  sample = 5000,
  n.chains = 4
)

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 1).
Chain 1:
Chain 1: Gradient evaluation took 0.003716 seconds
Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 37.16 seconds.
Chain 1: Adjust your expectations accordingly!
Chain 1:
Chain 1:
Chain 1: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 1: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 1: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 1: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 1: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 1: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 1: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 1: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 1: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 1: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 1: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 1: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 1:
Chain 1:  Elapsed Time: 237.107 seconds (Warm-up)
Chain 1:                453.893 seconds (Sampling)
Chain 1:                691 seconds (Total)
Chain 1:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 2).
Chain 2:
Chain 2: Gradient evaluation took 0.004776 seconds
Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 47.76 seconds.
Chain 2: Adjust your expectations accordingly!
Chain 2:
Chain 2:
Chain 2: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 2: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 2: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 2: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 2: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 2: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 2: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 2: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 2: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 2: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 2: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 2: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 2:
Chain 2:  Elapsed Time: 225.643 seconds (Warm-up)
Chain 2:                465.6 seconds (Sampling)
Chain 2:                691.243 seconds (Total)
Chain 2:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 3).
Chain 3:
Chain 3: Gradient evaluation took 0.003616 seconds
Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 36.16 seconds.
Chain 3: Adjust your expectations accordingly!
Chain 3:
Chain 3:
Chain 3: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 3: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 3: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 3: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 3: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 3: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 3: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 3: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 3: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 3: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 3: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 3: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 3:
Chain 3:  Elapsed Time: 232.705 seconds (Warm-up)
Chain 3:                459.817 seconds (Sampling)
Chain 3:                692.522 seconds (Total)
Chain 3:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 4).
Chain 4:
Chain 4: Gradient evaluation took 0.004374 seconds
Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 43.74 seconds.
Chain 4: Adjust your expectations accordingly!
Chain 4:
Chain 4:
Chain 4: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 4: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 4: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 4: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 4: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 4: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 4: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 4: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 4: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 4: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 4: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 4: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 4:
Chain 4:  Elapsed Time: 227.953 seconds (Warm-up)
Chain 4:                464.748 seconds (Sampling)
Chain 4:                692.701 seconds (Total)
Chain 4:
Computing post-estimation metrics (including lvs if requested)...

In [32]:
summary(fit_bayes_config_leader)

blavaan 0.5.10 ended normally after 5000 iterations

  Estimator                                      BAYES
  Optimization method                             MCMC
  Number of model parameters                       170

  Number of observations per group:
    Não                                            196
    Sim                                            127

  Statistic                                 MargLogLik         PPP
  Value                                     -10025.163       0.000

Parameter Estimates:



Group 1 [Não]:

Latent Variables:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional =~
    Q48                        1.000
    Q49                        1.046    0.080    0.896    1.211    1.000
    Q50                        0.881    0.073    0.745    1.030    1.000
    Q51                        0.910    0.072    0.776    1.058    1.000
    Q52                        0.887    0.073    0.748    1.039    1.000
    Q53                        0.879    0.085    0.718    1.051    1.000
    Q54                        0.828    0.081    0.674    0.991    1.000
  Regulacao_Emocional =~
    Q55                        1.000
    Q56                        1.108    0.116    0.906    1.365    1.000
    Q57                        1.072    0.121    0.858    1.338    1.000
    Q58                        1.017    0.114    0.818    1.264    1.000
    Q59                        1.169    0.123    0.955    1.436    1.000
    Q60                        1.165    0.123    0.953    1.433    1.000
  Consciencia_Social =~
    Q61                        1.000
    Q62                        0.973    0.064    0.856    1.107    1.000
    Q63                        1.061    0.065    0.942    1.195    1.000
    Q64                        0.984    0.068    0.858    1.125    1.000
  Autocontrole_Emocional =~
    Q65                        1.000
    Q66                        0.902    0.053    0.800    1.010    1.000
    Q67                        0.880    0.053    0.782    0.989    1.000
  Criatividade_Emocional =~
    Q68                        1.000
    Q69                        1.012    0.088    0.853    1.200    1.000
    Q70                        1.089    0.093    0.923    1.287    1.001
    Q71                        1.063    0.101    0.879    1.276    1.000
    Q72                        1.035    0.098    0.855    1.242    1.000
    Prior


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)

Covariances:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional ~~
    Regulaca_Emcnl             0.552    0.092    0.389    0.749    1.000
    Conscienci_Scl             0.511    0.081    0.368    0.687    1.000
    Autcntrl_Emcnl             0.550    0.094    0.382    0.749    1.000
    Criatvdd_Emcnl             0.551    0.088    0.396    0.740    1.000
  Regulacao_Emocional ~~
    Conscienci_Scl             0.475    0.081    0.332    0.649    1.001
    Autcntrl_Emcnl             0.508    0.091    0.347    0.706    1.001
    Criatvdd_Emcnl             0.504    0.087    0.352    0.692    1.001
  Consciencia_Social ~~
    Autcntrl_Emcnl             0.657    0.092    0.493    0.856    1.000
    Criatvdd_Emcnl             0.533    0.082    0.389    0.710    1.000
  Autocontrole_Emocional ~~
    Criatvdd_Emcnl             0.606    0.095    0.439    0.811    1.000
    Prior

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)

Intercepts:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               3.996    0.082    3.837    4.159    1.001    normal(0,32)
   .Q49               3.726    0.090    3.552    3.902    1.002    normal(0,32)
   .Q50               3.848    0.080    3.690    4.004    1.002    normal(0,32)
   .Q51               4.098    0.080    3.941    4.256    1.001    normal(0,32)
   .Q52               3.976    0.082    3.815    4.139    1.002    normal(0,32)
   .Q53               3.817    0.090    3.643    3.996    1.001    normal(0,32)
   .Q54               4.052    0.085    3.887    4.219    1.001    normal(0,32)
   .Q55               3.491    0.090    3.315    3.669    1.001    normal(0,32)
   .Q56               3.772    0.085    3.605    3.938    1.001    normal(0,32)
   .Q57               3.384    0.091    3.207    3.564    1.001    normal(0,32)
   .Q58               4.083    0.082    3.922    4.244    1.001    normal(0,32)
   .Q59               3.797    0.083    3.635    3.959    1.002    normal(0,32)
   .Q60               3.884    0.083    3.723    4.050    1.002    normal(0,32)
   .Q61               4.242    0.076    4.091    4.392    1.001    normal(0,32)
   .Q62               4.394    0.068    4.259    4.529    1.002    normal(0,32)
   .Q63               4.410    0.072    4.268    4.551    1.002    normal(0,32)
   .Q64               4.313    0.071    4.172    4.450    1.001    normal(0,32)
   .Q65               4.149    0.084    3.985    4.314    1.001    normal(0,32)
   .Q66               4.016    0.082    3.856    4.176    1.001    normal(0,32)
   .Q67               4.175    0.078    4.023    4.326    1.001    normal(0,32)
   .Q68               3.801    0.086    3.634    3.969    1.001    normal(0,32)
   .Q69               4.006    0.077    3.857    4.157    1.001    normal(0,32)
   .Q70               3.919    0.079    3.765    4.074    1.001    normal(0,32)
   .Q71               3.700    0.087    3.531    3.870    1.001    normal(0,32)
   .Q72               3.827    0.085    3.661    3.992    1.001    normal(0,32)
    Conscinc_Emcnl    0.000
    Regulaca_Emcnl    0.000
    Conscienci_Scl    0.000
    Autcntrl_Emcnl    0.000
    Criatvdd_Emcnl    0.000

Variances:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               0.384    0.052    0.292    0.494    1.000 gamma(1,.5)[sd]
   .Q49               0.556    0.069    0.434    0.703    1.000 gamma(1,.5)[sd]
   .Q50               0.538    0.063    0.427    0.672    1.000 gamma(1,.5)[sd]
   .Q51               0.488    0.059    0.385    0.613    1.000 gamma(1,.5)[sd]
   .Q52               0.577    0.066    0.460    0.719    1.000 gamma(1,.5)[sd]
   .Q53               0.865    0.096    0.694    1.073    1.000 gamma(1,.5)[sd]
   .Q54               0.772    0.086    0.619    0.956    1.000 gamma(1,.5)[sd]
   .Q55               0.889    0.104    0.705    1.111    1.000 gamma(1,.5)[sd]
   .Q56               0.532    0.065    0.416    0.673    1.000 gamma(1,.5)[sd]
   .Q57               0.764    0.088    0.608    0.953    1.000 gamma(1,.5)[sd]
   .Q58               0.548    0.063    0.437    0.685    1.000 gamma(1,.5)[sd]
   .Q59               0.363    0.051    0.273    0.473    1.000 gamma(1,.5)[sd]
   .Q60               0.383    0.052    0.290    0.496    1.000 gamma(1,.5)[sd]
   .Q61               0.363    0.044    0.285    0.457    1.000 gamma(1,.5)[sd]
   .Q62               0.207    0.028    0.157    0.267    1.000 gamma(1,.5)[sd]
   .Q63               0.153    0.025    0.107    0.208    1.000 gamma(1,.5)[sd]
   .Q64               0.249    0.032    0.193    0.317    1.000 gamma(1,.5)[sd]
   .Q65               0.232    0.046    0.149    0.328    1.000 gamma(1,.5)[sd]
   .Q66               0.372    0.050    0.284    0.480    1.000 gamma(1,.5)[sd]
   .Q67               0.278    0.044    0.197    0.371    1.000 gamma(1,.5)[sd]
   .Q68               0.632    0.076    0.500    0.793    1.000 gamma(1,.5)[sd]
   .Q69               0.365    0.048    0.280    0.468    1.000 gamma(1,.5)[sd]
   .Q70               0.310    0.044    0.231    0.404    1.000 gamma(1,.5)[sd]
   .Q71               0.605    0.072    0.477    0.761    1.000 gamma(1,.5)[sd]
   .Q72               0.583    0.069    0.461    0.728    1.000 gamma(1,.5)[sd]
    Conscinc_Emcnl    0.939    0.132    0.705    1.225    1.000 gamma(1,.5)[sd]
    Regulaca_Emcnl    0.730    0.146    0.469    1.042    1.001 gamma(1,.5)[sd]
    Conscienci_Scl    0.769    0.111    0.573    1.008    1.000 gamma(1,.5)[sd]
    Autcntrl_Emcnl    1.167    0.144    0.910    1.473    1.000 gamma(1,.5)[sd]
    Criatvdd_Emcnl    0.776    0.131    0.540    1.059    1.001 gamma(1,.5)[sd]


Group 2 [Sim]:

Latent Variables:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional =~
    Q48                        1.000
    Q49                        0.984    0.123    0.764    1.244    1.000
    Q50                        1.158    0.128    0.932    1.433    1.000
    Q51                        1.079    0.118    0.868    1.334    1.000
    Q52                        1.152    0.118    0.941    1.407    1.000
    Q53                        1.182    0.144    0.920    1.485    1.000
    Q54                        1.063    0.117    0.853    1.313    1.000
  Regulacao_Emocional =~
    Q55                        1.000
    Q56                        0.897    0.127    0.673    1.173    1.000
    Q57                        1.039    0.141    0.794    1.353    1.000
    Q58                        0.776    0.119    0.566    1.035    1.000
    Q59                        0.963    0.130    0.740    1.255    1.000
    Q60                        0.904    0.128    0.684    1.187    1.000
  Consciencia_Social =~
    Q61                        1.000
    Q62                        0.954    0.057    0.846    1.073    1.000
    Q63                        0.944    0.070    0.812    1.084    1.000
    Q64                        1.007    0.072    0.870    1.154    1.000
  Autocontrole_Emocional =~
    Q65                        1.000
    Q66                        0.918    0.073    0.782    1.071    1.000
    Q67                        0.918    0.079    0.772    1.081    1.000
  Criatividade_Emocional =~
    Q68                        1.000
    Q69                        1.310    0.161    1.050    1.676    1.000
    Q70                        1.356    0.192    1.039    1.782    1.000
    Q71                        1.247    0.165    0.980    1.615    1.000
    Q72                        1.269    0.175    0.978    1.665    1.000
    Prior


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)

Covariances:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional ~~
    Regulaca_Emcnl             0.254    0.077    0.119    0.421    1.000
    Conscienci_Scl             0.330    0.070    0.208    0.484    1.000
    Autcntrl_Emcnl             0.399    0.088    0.248    0.593    1.000
    Criatvdd_Emcnl             0.337    0.072    0.212    0.495    1.000
  Regulacao_Emocional ~~
    Conscienci_Scl             0.334    0.081    0.192    0.512    1.000
    Autcntrl_Emcnl             0.471    0.107    0.287    0.704    1.000
    Criatvdd_Emcnl             0.305    0.076    0.175    0.473    1.000
  Consciencia_Social ~~
    Autcntrl_Emcnl             0.595    0.097    0.424    0.806    1.000
    Criatvdd_Emcnl             0.360    0.071    0.236    0.515    1.000
  Autocontrole_Emocional ~~
    Criatvdd_Emcnl             0.408    0.084    0.262    0.593    1.000
    Prior

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)

Intercepts:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               4.203    0.090    4.027    4.379    1.000    normal(0,32)
   .Q49               4.094    0.097    3.904    4.283    1.000    normal(0,32)
   .Q50               3.998    0.102    3.798    4.195    1.000    normal(0,32)
   .Q51               4.290    0.093    4.108    4.472    1.000    normal(0,32)
   .Q52               4.180    0.093    3.996    4.361    1.000    normal(0,32)
   .Q53               4.030    0.113    3.808    4.250    1.000    normal(0,32)
   .Q54               4.337    0.092    4.158    4.518    1.000    normal(0,32)
   .Q55               3.882    0.108    3.669    4.094    1.000    normal(0,32)
   .Q56               4.086    0.097    3.896    4.277    1.000    normal(0,32)
   .Q57               3.708    0.107    3.499    3.919    1.000    normal(0,32)
   .Q58               4.338    0.086    4.170    4.507    1.000    normal(0,32)
   .Q59               4.086    0.092    3.904    4.268    1.000    normal(0,32)
   .Q60               4.173    0.091    3.996    4.353    1.000    normal(0,32)
   .Q61               4.488    0.079    4.335    4.642    1.001    normal(0,32)
   .Q62               4.582    0.074    4.436    4.727    1.001    normal(0,32)
   .Q63               4.582    0.079    4.427    4.736    1.001    normal(0,32)
   .Q64               4.441    0.083    4.279    4.603    1.001    normal(0,32)
   .Q65               4.290    0.098    4.098    4.485    1.001    normal(0,32)
   .Q66               4.141    0.092    3.961    4.323    1.000    normal(0,32)
   .Q67               4.267    0.094    4.081    4.452    1.001    normal(0,32)
   .Q68               4.140    0.089    3.963    4.314    1.000    normal(0,32)
   .Q69               4.235    0.083    4.070    4.400    1.000    normal(0,32)
   .Q70               4.077    0.101    3.879    4.276    1.000    normal(0,32)
   .Q71               4.180    0.085    4.012    4.348    1.000    normal(0,32)
   .Q72               4.180    0.092    4.000    4.360    1.000    normal(0,32)
    Conscinc_Emcnl    0.000
    Regulaca_Emcnl    0.000
    Conscienci_Scl    0.000
    Autcntrl_Emcnl    0.000
    Criatvdd_Emcnl    0.000

Variances:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               0.407    0.062    0.300    0.543    1.000 gamma(1,.5)[sd]
   .Q49               0.622    0.087    0.472    0.811    1.000 gamma(1,.5)[sd]
   .Q50               0.519    0.077    0.387    0.688    1.000 gamma(1,.5)[sd]
   .Q51               0.386    0.059    0.285    0.514    1.000 gamma(1,.5)[sd]
   .Q52               0.291    0.050    0.205    0.400    1.000 gamma(1,.5)[sd]
   .Q53               0.778    0.111    0.586    1.023    1.000 gamma(1,.5)[sd]
   .Q54               0.389    0.060    0.287    0.518    1.000 gamma(1,.5)[sd]
   .Q55               0.751    0.116    0.554    1.010    1.000 gamma(1,.5)[sd]
   .Q56               0.612    0.096    0.447    0.819    1.000 gamma(1,.5)[sd]
   .Q57               0.650    0.103    0.472    0.877    1.000 gamma(1,.5)[sd]
   .Q58               0.494    0.074    0.367    0.656    1.000 gamma(1,.5)[sd]
   .Q59               0.391    0.068    0.274    0.539    1.000 gamma(1,.5)[sd]
   .Q60               0.443    0.073    0.317    0.604    1.000 gamma(1,.5)[sd]
   .Q61               0.141    0.026    0.097    0.197    1.000 gamma(1,.5)[sd]
   .Q62               0.106    0.021    0.069    0.151    1.000 gamma(1,.5)[sd]
   .Q63               0.217    0.034    0.160    0.291    1.000 gamma(1,.5)[sd]
   .Q64               0.236    0.037    0.173    0.316    1.000 gamma(1,.5)[sd]
   .Q65               0.265    0.056    0.165    0.387    1.000 gamma(1,.5)[sd]
   .Q66               0.269    0.049    0.182    0.375    1.000 gamma(1,.5)[sd]
   .Q67               0.330    0.058    0.228    0.457    1.000 gamma(1,.5)[sd]
   .Q68               0.558    0.077    0.424    0.728    1.000 gamma(1,.5)[sd]
   .Q69               0.162    0.034    0.102    0.235    1.000 gamma(1,.5)[sd]
   .Q70               0.535    0.079    0.399    0.708    1.000 gamma(1,.5)[sd]
   .Q71               0.264    0.043    0.191    0.358    1.000 gamma(1,.5)[sd]
   .Q72               0.404    0.061    0.298    0.539    1.000 gamma(1,.5)[sd]
    Conscinc_Emcnl    0.608    0.123    0.394    0.877    1.000 gamma(1,.5)[sd]
    Regulaca_Emcnl    0.769    0.183    0.448    1.166    1.000 gamma(1,.5)[sd]
    Conscienci_Scl    0.638    0.096    0.472    0.846    1.000 gamma(1,.5)[sd]
    Autcntrl_Emcnl    0.958    0.156    0.685    1.297    1.000 gamma(1,.5)[sd]
    Criatvdd_Emcnl    0.430    0.107    0.242    0.660    1.000 gamma(1,.5)[sd]

In [26]:
fit_bayes_metric <- bcfa(
  modelo_emocional,
  data = dados,
  group = "Q4",
  group.equal = "loadings",
  burnin = 2000,
  sample = 5000,
  n.chains = 4
)

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 1).
Chain 1:
Chain 1: Gradient evaluation took 0.005139 seconds
Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 51.39 seconds.
Chain 1: Adjust your expectations accordingly!
Chain 1:
Chain 1:
Chain 1: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 1: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 1: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 1: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 1: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 1: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 1: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 1: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 1: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 1: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 1: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 1: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 1:
Chain 1:  Elapsed Time: 192.134 seconds (Warm-up)
Chain 1:                396.869 seconds (Sampling)
Chain 1:                589.003 seconds (Total)
Chain 1:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 2).
Chain 2:
Chain 2: Gradient evaluation took 0.003794 seconds
Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 37.94 seconds.
Chain 2: Adjust your expectations accordingly!
Chain 2:
Chain 2:
Chain 2: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 2: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 2: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 2: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 2: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 2: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 2: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 2: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 2: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 2: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 2: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 2: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 2:
Chain 2:  Elapsed Time: 189.377 seconds (Warm-up)
Chain 2:                409.177 seconds (Sampling)
Chain 2:                598.554 seconds (Total)
Chain 2:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 3).
Chain 3:
Chain 3: Gradient evaluation took 0.002915 seconds
Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 29.15 seconds.
Chain 3: Adjust your expectations accordingly!
Chain 3:
Chain 3:
Chain 3: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 3: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 3: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 3: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 3: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 3: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 3: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 3: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 3: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 3: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 3: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 3: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 3:
Chain 3:  Elapsed Time: 188.053 seconds (Warm-up)
Chain 3:                398.191 seconds (Sampling)
Chain 3:                586.244 seconds (Total)
Chain 3:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 4).
Chain 4:
Chain 4: Gradient evaluation took 0.003126 seconds
Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 31.26 seconds.
Chain 4: Adjust your expectations accordingly!
Chain 4:
Chain 4:
Chain 4: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 4: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 4: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 4: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 4: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 4: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 4: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 4: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 4: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 4: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 4: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 4: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 4:
Chain 4:  Elapsed Time: 191.654 seconds (Warm-up)
Chain 4:                402.444 seconds (Sampling)
Chain 4:                594.098 seconds (Total)
Chain 4:
Computing post-estimation metrics (including lvs if requested)...

In [33]:
summary(fit_bayes_metric)

blavaan 0.5.10 ended normally after 5000 iterations

  Estimator                                      BAYES
  Optimization method                             MCMC
  Number of model parameters                       170
  Number of equality constraints                    20

  Number of observations per group:
    Não                                            196
    Sim                                            127

  Statistic                                 MargLogLik         PPP
  Value                                      -9945.643       0.000

Parameter Estimates:



Group 1 [Não]:

Latent Variables:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional =~
    Q48                        1.000
    Q49     (.p2.)             1.015    0.066    0.889    1.150    1.000
    Q50     (.p3.)             0.957    0.063    0.838    1.084    1.000
    Q51     (.p4.)             0.950    0.060    0.836    1.072    1.000
    Q52     (.p5.)             0.968    0.059    0.859    1.089    1.000
    Q53     (.p6.)             0.964    0.071    0.828    1.109    1.000
    Q54     (.p7.)             0.901    0.063    0.781    1.029    1.000
  Regulacao_Emocional =~
    Q55                        1.000
    Q56     (.p9.)             1.002    0.079    0.858    1.169    1.000
    Q57     (.10.)             1.030    0.085    0.874    1.209    1.000
    Q58     (.11.)             0.904    0.077    0.762    1.066    1.001
    Q59     (.12.)             1.064    0.082    0.916    1.237    1.000
    Q60     (.13.)             1.042    0.082    0.893    1.214    1.000
  Consciencia_Social =~
    Q61                        1.000
    Q62     (.15.)             0.959    0.042    0.879    1.046    1.000
    Q63     (.16.)             1.013    0.046    0.925    1.107    1.000
    Q64     (.17.)             0.981    0.048    0.889    1.080    1.000
  Autocontrole_Emocional =~
    Q65                        1.000
    Q66     (.19.)             0.904    0.043    0.823    0.991    1.000
    Q67     (.20.)             0.890    0.044    0.807    0.979    1.000
  Criatividade_Emocional =~
    Q68                        1.000
    Q69     (.22.)             1.103    0.075    0.966    1.261    1.000
    Q70     (.23.)             1.155    0.084    1.004    1.329    1.000
    Q71     (.24.)             1.096    0.081    0.949    1.267    1.000
    Q72     (.25.)             1.093    0.083    0.942    1.268    1.000
    Prior


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)

Covariances:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional ~~
    Regulaca_Emcnl             0.576    0.088    0.419    0.764    1.000
    Conscienci_Scl             0.502    0.077    0.368    0.667    1.000
    Autcntrl_Emcnl             0.529    0.089    0.370    0.719    1.000
    Criatvdd_Emcnl             0.502    0.078    0.365    0.669    1.000
  Regulacao_Emocional ~~
    Conscienci_Scl             0.528    0.082    0.382    0.700    1.000
    Autcntrl_Emcnl             0.552    0.093    0.385    0.749    1.000
    Criatvdd_Emcnl             0.520    0.082    0.375    0.697    1.000
  Consciencia_Social ~~
    Autcntrl_Emcnl             0.670    0.091    0.510    0.865    1.000
    Criatvdd_Emcnl             0.517    0.075    0.383    0.679    1.000
  Autocontrole_Emocional ~~
    Criatvdd_Emcnl             0.571    0.087    0.416    0.758    1.000
    Prior

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)

Intercepts:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               3.994    0.080    3.837    4.152    1.002    normal(0,32)
   .Q49               3.724    0.086    3.555    3.892    1.001    normal(0,32)
   .Q50               3.847    0.082    3.687    4.009    1.001    normal(0,32)
   .Q51               4.097    0.080    3.940    4.255    1.001    normal(0,32)
   .Q52               3.974    0.084    3.810    4.139    1.001    normal(0,32)
   .Q53               3.816    0.092    3.636    3.995    1.001    normal(0,32)
   .Q54               4.051    0.086    3.881    4.219    1.001    normal(0,32)
   .Q55               3.490    0.093    3.310    3.672    1.001    normal(0,32)
   .Q56               3.771    0.084    3.607    3.936    1.001    normal(0,32)
   .Q57               3.383    0.092    3.204    3.563    1.001    normal(0,32)
   .Q58               4.082    0.080    3.926    4.242    1.001    normal(0,32)
   .Q59               3.796    0.083    3.635    3.961    1.001    normal(0,32)
   .Q60               3.883    0.082    3.725    4.044    1.001    normal(0,32)
   .Q61               4.240    0.076    4.090    4.390    1.001    normal(0,32)
   .Q62               4.393    0.069    4.256    4.527    1.001    normal(0,32)
   .Q63               4.408    0.070    4.271    4.545    1.001    normal(0,32)
   .Q64               4.311    0.072    4.171    4.454    1.001    normal(0,32)
   .Q65               4.147    0.084    3.985    4.312    1.001    normal(0,32)
   .Q66               4.015    0.083    3.853    4.178    1.001    normal(0,32)
   .Q67               4.174    0.078    4.021    4.329    1.001    normal(0,32)
   .Q68               3.801    0.083    3.638    3.963    1.001    normal(0,32)
   .Q69               4.005    0.078    3.853    4.159    1.001    normal(0,32)
   .Q70               3.918    0.079    3.767    4.072    1.001    normal(0,32)
   .Q71               3.699    0.085    3.534    3.869    1.001    normal(0,32)
   .Q72               3.827    0.085    3.661    3.994    1.001    normal(0,32)
    Conscinc_Emcnl    0.000
    Regulaca_Emcnl    0.000
    Conscienci_Scl    0.000
    Autcntrl_Emcnl    0.000
    Criatvdd_Emcnl    0.000

Variances:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               0.394    0.051    0.304    0.504    1.000 gamma(1,.5)[sd]
   .Q49               0.575    0.070    0.449    0.727    1.000 gamma(1,.5)[sd]
   .Q50               0.537    0.063    0.425    0.672    1.000 gamma(1,.5)[sd]
   .Q51               0.486    0.058    0.383    0.610    1.000 gamma(1,.5)[sd]
   .Q52               0.573    0.066    0.456    0.717    1.000 gamma(1,.5)[sd]
   .Q53               0.854    0.096    0.684    1.062    1.000 gamma(1,.5)[sd]
   .Q54               0.760    0.084    0.610    0.940    1.000 gamma(1,.5)[sd]
   .Q55               0.865    0.099    0.691    1.075    1.000 gamma(1,.5)[sd]
   .Q56               0.523    0.065    0.407    0.663    1.000 gamma(1,.5)[sd]
   .Q57               0.748    0.089    0.589    0.940    1.000 gamma(1,.5)[sd]
   .Q58               0.556    0.065    0.441    0.694    1.000 gamma(1,.5)[sd]
   .Q59               0.373    0.051    0.281    0.482    1.000 gamma(1,.5)[sd]
   .Q60               0.395    0.053    0.301    0.508    1.000 gamma(1,.5)[sd]
   .Q61               0.361    0.044    0.283    0.457    1.000 gamma(1,.5)[sd]
   .Q62               0.204    0.028    0.155    0.264    1.000 gamma(1,.5)[sd]
   .Q63               0.159    0.025    0.115    0.212    1.000 gamma(1,.5)[sd]
   .Q64               0.247    0.032    0.190    0.315    1.000 gamma(1,.5)[sd]
   .Q65               0.236    0.045    0.153    0.330    1.000 gamma(1,.5)[sd]
   .Q66               0.372    0.049    0.285    0.477    1.000 gamma(1,.5)[sd]
   .Q67               0.275    0.044    0.196    0.367    1.000 gamma(1,.5)[sd]
   .Q68               0.643    0.075    0.509    0.804    1.000 gamma(1,.5)[sd]
   .Q69               0.358    0.046    0.275    0.457    1.000 gamma(1,.5)[sd]
   .Q70               0.305    0.043    0.228    0.398    1.000 gamma(1,.5)[sd]
   .Q71               0.609    0.071    0.483    0.761    1.000 gamma(1,.5)[sd]
   .Q72               0.584    0.070    0.460    0.733    1.000 gamma(1,.5)[sd]
    Conscinc_Emcnl    0.865    0.116    0.661    1.109    1.000 gamma(1,.5)[sd]
    Regulaca_Emcnl    0.861    0.138    0.616    1.164    1.000 gamma(1,.5)[sd]
    Conscienci_Scl    0.801    0.101    0.622    1.018    1.000 gamma(1,.5)[sd]
    Autcntrl_Emcnl    1.157    0.138    0.910    1.453    1.000 gamma(1,.5)[sd]
    Criatvdd_Emcnl    0.696    0.108    0.503    0.927    1.000 gamma(1,.5)[sd]


Group 2 [Sim]:

Latent Variables:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional =~
    Q48                        1.000
    Q49     (.p2.)             1.015    0.066    0.889    1.150    1.000
    Q50     (.p3.)             0.957    0.063    0.838    1.084    1.000
    Q51     (.p4.)             0.950    0.060    0.836    1.072    1.000
    Q52     (.p5.)             0.968    0.059    0.859    1.089    1.000
    Q53     (.p6.)             0.964    0.071    0.828    1.109    1.000
    Q54     (.p7.)             0.901    0.063    0.781    1.029    1.000
  Regulacao_Emocional =~
    Q55                        1.000
    Q56     (.p9.)             1.002    0.079    0.858    1.169    1.000
    Q57     (.10.)             1.030    0.085    0.874    1.209    1.000
    Q58     (.11.)             0.904    0.077    0.762    1.066    1.001
    Q59     (.12.)             1.064    0.082    0.916    1.237    1.000
    Q60     (.13.)             1.042    0.082    0.893    1.214    1.000
  Consciencia_Social =~
    Q61                        1.000
    Q62     (.15.)             0.959    0.042    0.879    1.046    1.000
    Q63     (.16.)             1.013    0.046    0.925    1.107    1.000
    Q64     (.17.)             0.981    0.048    0.889    1.080    1.000
  Autocontrole_Emocional =~
    Q65                        1.000
    Q66     (.19.)             0.904    0.043    0.823    0.991    1.000
    Q67     (.20.)             0.890    0.044    0.807    0.979    1.000
  Criatividade_Emocional =~
    Q68                        1.000
    Q69     (.22.)             1.103    0.075    0.966    1.261    1.000
    Q70     (.23.)             1.155    0.084    1.004    1.329    1.000
    Q71     (.24.)             1.096    0.081    0.949    1.267    1.000
    Q72     (.25.)             1.093    0.083    0.942    1.268    1.000
    Prior































Covariances:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional ~~
    Regulaca_Emcnl             0.256    0.073    0.124    0.411    1.000
    Conscienci_Scl             0.366    0.074    0.237    0.526    1.000
    Autcntrl_Emcnl             0.455    0.094    0.288    0.656    1.000
    Criatvdd_Emcnl             0.439    0.079    0.302    0.610    1.000
  Regulacao_Emocional ~~
    Conscienci_Scl             0.302    0.069    0.180    0.452    1.000
    Autcntrl_Emcnl             0.437    0.092    0.277    0.639    1.000
    Criatvdd_Emcnl             0.318    0.070    0.198    0.471    1.000
  Consciencia_Social ~~
    Autcntrl_Emcnl             0.598    0.094    0.434    0.806    1.000
    Criatvdd_Emcnl             0.408    0.071    0.285    0.566    1.000
  Autocontrole_Emocional ~~
    Criatvdd_Emcnl             0.475    0.087    0.325    0.664    1.000
    Prior

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)

Intercepts:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               4.204    0.097    4.015    4.395    1.001    normal(0,32)
   .Q49               4.094    0.106    3.885    4.301    1.001    normal(0,32)
   .Q50               3.999    0.099    3.805    4.193    1.001    normal(0,32)
   .Q51               4.291    0.095    4.105    4.479    1.001    normal(0,32)
   .Q52               4.180    0.092    4.003    4.361    1.001    normal(0,32)
   .Q53               4.031    0.112    3.813    4.251    1.001    normal(0,32)
   .Q54               4.338    0.092    4.159    4.518    1.001    normal(0,32)
   .Q55               3.883    0.108    3.672    4.094    1.001    normal(0,32)
   .Q56               4.087    0.101    3.889    4.283    1.001    normal(0,32)
   .Q57               3.709    0.105    3.502    3.916    1.000    normal(0,32)
   .Q58               4.339    0.090    4.164    4.516    1.000    normal(0,32)
   .Q59               4.088    0.094    3.903    4.272    1.000    normal(0,32)
   .Q60               4.174    0.095    3.983    4.358    1.001    normal(0,32)
   .Q61               4.488    0.079    4.333    4.644    1.001    normal(0,32)
   .Q62               4.582    0.075    4.436    4.730    1.001    normal(0,32)
   .Q63               4.583    0.083    4.418    4.748    1.001    normal(0,32)
   .Q64               4.441    0.083    4.277    4.603    1.001    normal(0,32)
   .Q65               4.291    0.102    4.091    4.495    1.001    normal(0,32)
   .Q66               4.142    0.095    3.958    4.328    1.001    normal(0,32)
   .Q67               4.268    0.096    4.082    4.456    1.001    normal(0,32)
   .Q68               4.141    0.094    3.956    4.326    1.001    normal(0,32)
   .Q69               4.236    0.083    4.073    4.397    1.001    normal(0,32)
   .Q70               4.078    0.101    3.879    4.277    1.001    normal(0,32)
   .Q71               4.181    0.087    4.011    4.352    1.001    normal(0,32)
   .Q72               4.181    0.092    3.999    4.361    1.001    normal(0,32)
    Conscinc_Emcnl    0.000
    Regulaca_Emcnl    0.000
    Conscienci_Scl    0.000
    Autcntrl_Emcnl    0.000
    Criatvdd_Emcnl    0.000

Variances:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               0.384    0.059    0.282    0.512    1.000 gamma(1,.5)[sd]
   .Q49               0.604    0.087    0.455    0.796    1.000 gamma(1,.5)[sd]
   .Q50               0.522    0.075    0.394    0.686    1.000 gamma(1,.5)[sd]
   .Q51               0.387    0.059    0.287    0.515    1.000 gamma(1,.5)[sd]
   .Q52               0.309    0.050    0.222    0.417    1.000 gamma(1,.5)[sd]
   .Q53               0.797    0.111    0.607    1.038    1.000 gamma(1,.5)[sd]
   .Q54               0.404    0.060    0.301    0.538    1.000 gamma(1,.5)[sd]
   .Q55               0.791    0.116    0.594    1.043    1.000 gamma(1,.5)[sd]
   .Q56               0.633    0.095    0.469    0.840    1.000 gamma(1,.5)[sd]
   .Q57               0.687    0.104    0.508    0.912    1.000 gamma(1,.5)[sd]
   .Q58               0.474    0.071    0.352    0.629    1.000 gamma(1,.5)[sd]
   .Q59               0.372    0.062    0.264    0.506    1.000 gamma(1,.5)[sd]
   .Q60               0.419    0.068    0.302    0.569    1.000 gamma(1,.5)[sd]
   .Q61               0.143    0.025    0.098    0.198    1.000 gamma(1,.5)[sd]
   .Q62               0.104    0.020    0.069    0.147    1.000 gamma(1,.5)[sd]
   .Q63               0.212    0.033    0.156    0.285    1.000 gamma(1,.5)[sd]
   .Q64               0.240    0.037    0.177    0.321    1.000 gamma(1,.5)[sd]
   .Q65               0.258    0.053    0.165    0.372    1.000 gamma(1,.5)[sd]
   .Q66               0.269    0.049    0.185    0.376    1.000 gamma(1,.5)[sd]
   .Q67               0.333    0.057    0.235    0.459    1.000 gamma(1,.5)[sd]
   .Q68               0.550    0.077    0.418    0.722    1.000 gamma(1,.5)[sd]
   .Q69               0.165    0.032    0.108    0.234    1.000 gamma(1,.5)[sd]
   .Q70               0.533    0.077    0.400    0.701    1.000 gamma(1,.5)[sd]
   .Q71               0.264    0.042    0.191    0.357    1.000 gamma(1,.5)[sd]
   .Q72               0.404    0.060    0.300    0.535    1.000 gamma(1,.5)[sd]
    Conscinc_Emcnl    0.766    0.120    0.559    1.029    1.000 gamma(1,.5)[sd]
    Regulaca_Emcnl    0.638    0.121    0.432    0.904    1.000 gamma(1,.5)[sd]
    Conscienci_Scl    0.625    0.090    0.470    0.823    1.000 gamma(1,.5)[sd]
    Autcntrl_Emcnl    0.987    0.145    0.739    1.309    1.000 gamma(1,.5)[sd]
    Criatvdd_Emcnl    0.559    0.098    0.389    0.776    1.000 gamma(1,.5)[sd]

In [27]:
fit_bayes_leader <- bcfa(
  modelo_emocional,
  data = dados,
  group = "Q4",
  burnin = 2000,
  sample = 5000,
  n.chains = 4,
  group.equal = c("loadings", "intercepts")
)

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 1).
Chain 1:
Chain 1: Gradient evaluation took 0.004811 seconds
Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 48.11 seconds.
Chain 1: Adjust your expectations accordingly!
Chain 1:
Chain 1:
Chain 1: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 1: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 1: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 1: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 1: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 1: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 1: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 1: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 1: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 1: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 1: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 1: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 1:
Chain 1:  Elapsed Time: 174.891 seconds (Warm-up)
Chain 1:                420.379 seconds (Sampling)
Chain 1:                595.27 seconds (Total)
Chain 1:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 2).
Chain 2:
Chain 2: Gradient evaluation took 0.004819 seconds
Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 48.19 seconds.
Chain 2: Adjust your expectations accordingly!
Chain 2:
Chain 2:
Chain 2: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 2: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 2: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 2: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 2: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 2: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 2: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 2: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 2: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 2: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 2: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 2: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 2:
Chain 2:  Elapsed Time: 187.874 seconds (Warm-up)
Chain 2:                404.594 seconds (Sampling)
Chain 2:                592.468 seconds (Total)
Chain 2:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 3).
Chain 3:
Chain 3: Gradient evaluation took 0.003752 seconds
Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 37.52 seconds.
Chain 3: Adjust your expectations accordingly!
Chain 3:
Chain 3:
Chain 3: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 3: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 3: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 3: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 3: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 3: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 3: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 3: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 3: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 3: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 3: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 3: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 3:
Chain 3:  Elapsed Time: 185.655 seconds (Warm-up)
Chain 3:                376.032 seconds (Sampling)
Chain 3:                561.687 seconds (Total)
Chain 3:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 4).
Chain 4:
Chain 4: Gradient evaluation took 0.005389 seconds
Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 53.89 seconds.
Chain 4: Adjust your expectations accordingly!
Chain 4:
Chain 4:
Chain 4: Iteration:    1 / 7000 [  0%]  (Warmup)
Chain 4: Iteration:  700 / 7000 [ 10%]  (Warmup)
Chain 4: Iteration: 1400 / 7000 [ 20%]  (Warmup)
Chain 4: Iteration: 2001 / 7000 [ 28%]  (Sampling)
Chain 4: Iteration: 2700 / 7000 [ 38%]  (Sampling)
Chain 4: Iteration: 3400 / 7000 [ 48%]  (Sampling)
Chain 4: Iteration: 4100 / 7000 [ 58%]  (Sampling)
Chain 4: Iteration: 4800 / 7000 [ 68%]  (Sampling)
Chain 4: Iteration: 5500 / 7000 [ 78%]  (Sampling)
Chain 4: Iteration: 6200 / 7000 [ 88%]  (Sampling)
Chain 4: Iteration: 6900 / 7000 [ 98%]  (Sampling)
Chain 4: Iteration: 7000 / 7000 [100%]  (Sampling)
Chain 4:
Chain 4:  Elapsed Time: 185.343 seconds (Warm-up)
Chain 4:                456.829 seconds (Sampling)
Chain 4:                642.172 seconds (Total)
Chain 4:
Computing post-estimation metrics (including lvs if requested)...

In [43]:
fit_bayes_leader

blavaan 0.5.10 ended normally after 5000 iterations

  Estimator                                      BAYES
  Optimization method                             MCMC
  Number of model parameters                       175
  Number of equality constraints                    45

  Number of observations per group:
    Não                                            196
    Sim                                            127

  Statistic                                 MargLogLik         PPP
  Value                                      -9832.105       0.000

In [34]:
summary(fit_bayes_leader)

blavaan 0.5.10 ended normally after 5000 iterations

  Estimator                                      BAYES
  Optimization method                             MCMC
  Number of model parameters                       175
  Number of equality constraints                    45

  Number of observations per group:
    Não                                            196
    Sim                                            127

  Statistic                                 MargLogLik         PPP
  Value                                      -9832.105       0.000

Parameter Estimates:



Group 1 [Não]:

Latent Variables:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional =~
    Q48                        1.000
    Q49     (.p2.)             1.024    0.066    0.900    1.159    1.000
    Q50     (.p3.)             0.952    0.061    0.835    1.076    1.000
    Q51     (.p4.)             0.948    0.059    0.837    1.068    1.000
    Q52     (.p5.)             0.966    0.058    0.857    1.086    1.000
    Q53     (.p6.)             0.964    0.071    0.827    1.108    1.000
    Q54     (.p7.)             0.907    0.062    0.789    1.033    1.000
  Regulacao_Emocional =~
    Q55                        1.000
    Q56     (.p9.)             0.992    0.077    0.852    1.155    1.000
    Q57     (.10.)             1.020    0.083    0.868    1.199    1.000
    Q58     (.11.)             0.890    0.075    0.753    1.049    1.000
    Q59     (.12.)             1.046    0.080    0.901    1.214    1.000
    Q60     (.13.)             1.026    0.079    0.882    1.194    1.000
  Consciencia_Social =~
    Q61                        1.000
    Q62     (.15.)             0.955    0.041    0.877    1.038    1.000
    Q63     (.16.)             1.006    0.044    0.923    1.096    1.000
    Q64     (.17.)             0.971    0.047    0.884    1.067    1.000
  Autocontrole_Emocional =~
    Q65                        1.000
    Q66     (.19.)             0.903    0.042    0.823    0.987    1.000
    Q67     (.20.)             0.887    0.043    0.805    0.973    1.000
  Criatividade_Emocional =~
    Q68                        1.000
    Q69     (.22.)             1.081    0.071    0.950    1.229    1.000
    Q70     (.23.)             1.124    0.078    0.981    1.287    1.000
    Q71     (.24.)             1.102    0.079    0.956    1.265    1.000
    Q72     (.25.)             1.086    0.079    0.941    1.249    1.000
    Prior


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)


    normal(0,10)
    normal(0,10)
    normal(0,10)
    normal(0,10)

Covariances:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional ~~
    Regulaca_Emcnl             0.583    0.089    0.427    0.773    1.000
    Conscienci_Scl             0.503    0.077    0.369    0.668    1.000
    Autcntrl_Emcnl             0.528    0.088    0.369    0.715    1.000
    Criatvdd_Emcnl             0.508    0.078    0.371    0.675    1.000
  Regulacao_Emocional ~~
    Conscienci_Scl             0.537    0.083    0.390    0.715    1.000
    Autcntrl_Emcnl             0.559    0.093    0.393    0.758    1.000
    Criatvdd_Emcnl             0.534    0.084    0.387    0.716    1.000
  Consciencia_Social ~~
    Autcntrl_Emcnl             0.673    0.090    0.514    0.865    1.000
    Criatvdd_Emcnl             0.527    0.076    0.391    0.690    1.000
  Autocontrole_Emocional ~~
    Criatvdd_Emcnl             0.580    0.088    0.423    0.766    1.000
    Prior

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)

Intercepts:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48     (.66.)    3.983    0.076    3.833    4.132    1.001    normal(0,32)
   .Q49     (.67.)    3.772    0.081    3.612    3.930    1.001    normal(0,32)
   .Q50     (.68.)    3.817    0.076    3.668    3.965    1.001    normal(0,32)
   .Q51     (.69.)    4.082    0.074    3.935    4.228    1.001    normal(0,32)
   .Q52     (.70.)    3.962    0.075    3.814    4.109    1.001    normal(0,32)
   .Q53     (.71.)    3.810    0.082    3.647    3.972    1.001    normal(0,32)
   .Q54     (.72.)    4.090    0.075    3.944    4.237    1.000    normal(0,32)
   .Q55     (.73.)    3.526    0.085    3.356    3.693    1.001    normal(0,32)
   .Q56     (.74.)    3.775    0.079    3.620    3.930    1.000    normal(0,32)
   .Q57     (.75.)    3.389    0.084    3.225    3.553    1.001    normal(0,32)
   .Q58     (.76.)    4.076    0.073    3.931    4.216    1.001    normal(0,32)
   .Q59     (.77.)    3.785    0.079    3.629    3.937    1.001    normal(0,32)
   .Q60     (.78.)    3.874    0.078    3.718    4.024    1.000    normal(0,32)
   .Q61     (.79.)    4.275    0.072    4.133    4.416    1.001    normal(0,32)
   .Q62     (.80.)    4.397    0.067    4.266    4.529    1.001    normal(0,32)
   .Q63     (.81.)    4.402    0.070    4.266    4.538    1.001    normal(0,32)
   .Q64     (.82.)    4.288    0.069    4.152    4.426    1.001    normal(0,32)
   .Q65     (.83.)    4.152    0.084    3.987    4.316    1.000    normal(0,32)
   .Q66     (.84.)    4.018    0.079    3.861    4.171    1.000    normal(0,32)
   .Q67     (.85.)    4.165    0.077    4.014    4.313    1.000    normal(0,32)
   .Q68     (.86.)    3.827    0.076    3.676    3.973    1.001    normal(0,32)
   .Q69     (.87.)    3.964    0.074    3.817    4.107    1.001    normal(0,32)
   .Q70     (.88.)    3.876    0.076    3.725    4.023    1.001    normal(0,32)
   .Q71     (.89.)    3.803    0.079    3.647    3.953    1.001    normal(0,32)
   .Q72     (.90.)    3.851    0.078    3.694    4.003    1.001    normal(0,32)
    Cnscn_E           0.000
    Rglc_Em           0.000
    Cnscn_S           0.000
    Atcnt_E           0.000
    Crtvd_E           0.000

Variances:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               0.394    0.051    0.303    0.502    1.000 gamma(1,.5)[sd]
   .Q49               0.573    0.069    0.450    0.722    1.000 gamma(1,.5)[sd]
   .Q50               0.538    0.064    0.425    0.672    1.000 gamma(1,.5)[sd]
   .Q51               0.485    0.058    0.382    0.609    1.000 gamma(1,.5)[sd]
   .Q52               0.572    0.067    0.454    0.716    1.000 gamma(1,.5)[sd]
   .Q53               0.853    0.096    0.684    1.062    1.000 gamma(1,.5)[sd]
   .Q54               0.760    0.085    0.610    0.944    1.000 gamma(1,.5)[sd]
   .Q55               0.861    0.100    0.685    1.075    1.000 gamma(1,.5)[sd]
   .Q56               0.520    0.065    0.406    0.661    1.000 gamma(1,.5)[sd]
   .Q57               0.743    0.086    0.591    0.927    1.000 gamma(1,.5)[sd]
   .Q58               0.557    0.066    0.441    0.697    1.000 gamma(1,.5)[sd]
   .Q59               0.374    0.051    0.283    0.482    1.000 gamma(1,.5)[sd]
   .Q60               0.396    0.053    0.305    0.509    1.000 gamma(1,.5)[sd]
   .Q61               0.360    0.043    0.284    0.452    1.000 gamma(1,.5)[sd]
   .Q62               0.203    0.028    0.154    0.263    1.000 gamma(1,.5)[sd]
   .Q63               0.159    0.025    0.114    0.212    1.000 gamma(1,.5)[sd]
   .Q64               0.248    0.032    0.192    0.316    1.000 gamma(1,.5)[sd]
   .Q65               0.234    0.045    0.153    0.328    1.000 gamma(1,.5)[sd]
   .Q66               0.371    0.048    0.285    0.474    1.000 gamma(1,.5)[sd]
   .Q67               0.275    0.043    0.198    0.365    1.000 gamma(1,.5)[sd]
   .Q68               0.637    0.075    0.505    0.795    1.000 gamma(1,.5)[sd]
   .Q69               0.361    0.046    0.279    0.461    1.000 gamma(1,.5)[sd]
   .Q70               0.312    0.044    0.233    0.406    1.000 gamma(1,.5)[sd]
   .Q71               0.617    0.073    0.486    0.775    1.000 gamma(1,.5)[sd]
   .Q72               0.581    0.069    0.459    0.729    1.000 gamma(1,.5)[sd]
    Conscinc_Emcnl    0.863    0.115    0.660    1.108    1.000 gamma(1,.5)[sd]
    Regulaca_Emcnl    0.884    0.142    0.631    1.188    1.000 gamma(1,.5)[sd]
    Conscienci_Scl    0.810    0.100    0.633    1.023    1.000 gamma(1,.5)[sd]
    Autcntrl_Emcnl    1.160    0.138    0.914    1.455    1.000 gamma(1,.5)[sd]
    Criatvdd_Emcnl    0.715    0.109    0.521    0.950    1.001 gamma(1,.5)[sd]


Group 2 [Sim]:

Latent Variables:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional =~
    Q48                        1.000
    Q49     (.p2.)             1.024    0.066    0.900    1.159    1.000
    Q50     (.p3.)             0.952    0.061    0.835    1.076    1.000
    Q51     (.p4.)             0.948    0.059    0.837    1.068    1.000
    Q52     (.p5.)             0.966    0.058    0.857    1.086    1.000
    Q53     (.p6.)             0.964    0.071    0.827    1.108    1.000
    Q54     (.p7.)             0.907    0.062    0.789    1.033    1.000
  Regulacao_Emocional =~
    Q55                        1.000
    Q56     (.p9.)             0.992    0.077    0.852    1.155    1.000
    Q57     (.10.)             1.020    0.083    0.868    1.199    1.000
    Q58     (.11.)             0.890    0.075    0.753    1.049    1.000
    Q59     (.12.)             1.046    0.080    0.901    1.214    1.000
    Q60     (.13.)             1.026    0.079    0.882    1.194    1.000
  Consciencia_Social =~
    Q61                        1.000
    Q62     (.15.)             0.955    0.041    0.877    1.038    1.000
    Q63     (.16.)             1.006    0.044    0.923    1.096    1.000
    Q64     (.17.)             0.971    0.047    0.884    1.067    1.000
  Autocontrole_Emocional =~
    Q65                        1.000
    Q66     (.19.)             0.903    0.042    0.823    0.987    1.000
    Q67     (.20.)             0.887    0.043    0.805    0.973    1.000
  Criatividade_Emocional =~
    Q68                        1.000
    Q69     (.22.)             1.081    0.071    0.950    1.229    1.000
    Q70     (.23.)             1.124    0.078    0.981    1.287    1.000
    Q71     (.24.)             1.102    0.079    0.956    1.265    1.000
    Q72     (.25.)             1.086    0.079    0.941    1.249    1.000
    Prior































Covariances:
                            Estimate  Post.SD pi.lower pi.upper     Rhat
  Consciencia_Emocional ~~
    Regulaca_Emcnl             0.259    0.074    0.125    0.416    1.000
    Conscienci_Scl             0.366    0.073    0.235    0.524    1.000
    Autcntrl_Emcnl             0.453    0.093    0.286    0.653    1.000
    Criatvdd_Emcnl             0.441    0.078    0.304    0.611    1.000
  Regulacao_Emocional ~~
    Conscienci_Scl             0.307    0.069    0.184    0.456    1.000
    Autcntrl_Emcnl             0.442    0.091    0.281    0.638    1.000
    Criatvdd_Emcnl             0.325    0.070    0.201    0.477    1.000
  Consciencia_Social ~~
    Autcntrl_Emcnl             0.600    0.093    0.436    0.802    1.000
    Criatvdd_Emcnl             0.414    0.070    0.292    0.566    1.000
  Autocontrole_Emocional ~~
    Criatvdd_Emcnl             0.480    0.086    0.329    0.665    1.000
    Prior

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)
     lkj_corr(1)

     lkj_corr(1)

Intercepts:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48     (.66.)    3.983    0.076    3.833    4.132    1.001
   .Q49     (.67.)    3.772    0.081    3.612    3.930    1.001
   .Q50     (.68.)    3.817    0.076    3.668    3.965    1.001
   .Q51     (.69.)    4.082    0.074    3.935    4.228    1.001
   .Q52     (.70.)    3.962    0.075    3.814    4.109    1.001
   .Q53     (.71.)    3.810    0.082    3.647    3.972    1.001
   .Q54     (.72.)    4.090    0.075    3.944    4.237    1.000
   .Q55     (.73.)    3.526    0.085    3.356    3.693    1.001
   .Q56     (.74.)    3.775    0.079    3.620    3.930    1.000
   .Q57     (.75.)    3.389    0.084    3.225    3.553    1.001
   .Q58     (.76.)    4.076    0.073    3.931    4.216    1.001
   .Q59     (.77.)    3.785    0.079    3.629    3.937    1.001
   .Q60     (.78.)    3.874    0.078    3.718    4.024    1.000
   .Q61     (.79.)    4.275    0.072    4.133    4.416    1.001
   .Q62     (.80.)    4.397    0.067    4.266    4.529    1.001
   .Q63     (.81.)    4.402    0.070    4.266    4.538    1.001
   .Q64     (.82.)    4.288    0.069    4.152    4.426    1.001
   .Q65     (.83.)    4.152    0.084    3.987    4.316    1.000
   .Q66     (.84.)    4.018    0.079    3.861    4.171    1.000
   .Q67     (.85.)    4.165    0.077    4.014    4.313    1.000
   .Q68     (.86.)    3.827    0.076    3.676    3.973    1.001
   .Q69     (.87.)    3.964    0.074    3.817    4.107    1.001
   .Q70     (.88.)    3.876    0.076    3.725    4.023    1.001
   .Q71     (.89.)    3.803    0.079    3.647    3.953    1.001
   .Q72     (.90.)    3.851    0.078    3.694    4.003    1.001
    Cnscn_E           0.237    0.107    0.030    0.448    1.000    normal(0,10)
    Rglc_Em           0.304    0.105    0.101    0.513    1.001    normal(0,10)
    Cnscn_S           0.190    0.100   -0.006    0.383    1.000    normal(0,10)
    Atcnt_E           0.132    0.125   -0.111    0.376    1.000    normal(0,10)
    Crtvd_E           0.280    0.096    0.093    0.473    1.001    normal(0,10)

Variances:
                   Estimate  Post.SD pi.lower pi.upper     Rhat    Prior
   .Q48               0.383    0.059    0.281    0.511    1.000 gamma(1,.5)[sd]
   .Q49               0.611    0.088    0.459    0.807    1.000 gamma(1,.5)[sd]
   .Q50               0.524    0.076    0.394    0.689    1.000 gamma(1,.5)[sd]
   .Q51               0.386    0.057    0.287    0.512    1.000 gamma(1,.5)[sd]
   .Q52               0.308    0.049    0.223    0.415    1.000 gamma(1,.5)[sd]
   .Q53               0.794    0.110    0.604    1.031    1.000 gamma(1,.5)[sd]
   .Q54               0.403    0.060    0.299    0.533    1.000 gamma(1,.5)[sd]
   .Q55               0.786    0.115    0.586    1.038    1.000 gamma(1,.5)[sd]
   .Q56               0.629    0.095    0.466    0.839    1.000 gamma(1,.5)[sd]
   .Q57               0.681    0.102    0.504    0.901    1.000 gamma(1,.5)[sd]
   .Q58               0.473    0.070    0.351    0.626    1.000 gamma(1,.5)[sd]
   .Q59               0.373    0.063    0.264    0.511    1.000 gamma(1,.5)[sd]
   .Q60               0.419    0.067    0.302    0.565    1.000 gamma(1,.5)[sd]
   .Q61               0.143    0.025    0.098    0.198    1.000 gamma(1,.5)[sd]
   .Q62               0.103    0.020    0.069    0.147    1.000 gamma(1,.5)[sd]
   .Q63               0.211    0.033    0.154    0.284    1.000 gamma(1,.5)[sd]
   .Q64               0.241    0.037    0.177    0.324    1.000 gamma(1,.5)[sd]
   .Q65               0.256    0.053    0.162    0.368    1.000 gamma(1,.5)[sd]
   .Q66               0.267    0.048    0.185    0.370    1.000 gamma(1,.5)[sd]
   .Q67               0.333    0.056    0.237    0.456    1.000 gamma(1,.5)[sd]
   .Q68               0.548    0.078    0.415    0.717    1.000 gamma(1,.5)[sd]
   .Q69               0.168    0.033    0.111    0.238    1.000 gamma(1,.5)[sd]
   .Q70               0.548    0.079    0.413    0.722    1.000 gamma(1,.5)[sd]
   .Q71               0.270    0.045    0.194    0.368    1.000 gamma(1,.5)[sd]
   .Q72               0.403    0.060    0.299    0.535    1.000 gamma(1,.5)[sd]
    Conscinc_Emcnl    0.763    0.118    0.561    1.021    1.000 gamma(1,.5)[sd]
    Regulaca_Emcnl    0.654    0.123    0.444    0.920    1.000 gamma(1,.5)[sd]
    Conscienci_Scl    0.631    0.089    0.475    0.828    1.000 gamma(1,.5)[sd]
    Autcntrl_Emcnl    0.988    0.143    0.741    1.300    1.000 gamma(1,.5)[sd]
    Criatvdd_Emcnl    0.568    0.098    0.401    0.784    1.000 gamma(1,.5)[sd]

Foi conduzida uma análise de invariância de medida Bayesiana para avaliar a equivalência do instrumento de inteligência emocional entre profissionais com função de liderança (n = 127) e sem função de liderança (n = 196). Inicialmente, o modelo configural apresentou adequada representação da estrutura fatorial em ambos os grupos, com cargas fatoriais elevadas e intervalos de credibilidade que não incluíram zero. Em seguida, o modelo métrico, no qual as cargas fatoriais foram restringidas à igualdade entre os grupos, apresentou melhora no ajuste Bayesiano, conforme indicado pelo aumento do logaritmo da verossimilhança marginal. Por fim, o modelo escalar, com restrição adicional dos interceptos dos itens, manteve estabilidade das estimativas e apresentou o melhor ajuste relativo. Esses resultados fornecem evidência robusta de invariância configural, métrica e escalar do instrumento entre indivíduos com e sem função de liderança, permitindo a comparação válida de médias latentes entre os grupos.

In [40]:
parameterEstimates(
  fit_bayes_leader,
  ci = TRUE,
  level = 0.95
) %>%
  filter(op == "~1")

   lhs                    op rhs block group label est
1  Q48                    ~1     1     1     .p66. 3.9831675
2  Q49                    ~1     1     1     .p67. 3.7717275
3  Q50                    ~1     1     1     .p68. 3.8169089
4  Q51                    ~1     1     1     .p69. 4.0824878
5  Q52                    ~1     1     1     .p70. 3.9618370
6  Q53                    ~1     1     1     .p71. 3.8099404
7  Q54                    ~1     1     1     .p72. 4.0902097
8  Q55                    ~1     1     1     .p73. 3.5255858
9  Q56                    ~1     1     1     .p74. 3.7753546
10 Q57                    ~1     1     1     .p75. 3.3889286
11 Q58                    ~1     1     1     .p76. 4.0758117
12 Q59                    ~1     1     1     .p77. 3.7849402
13 Q60                    ~1     1     1     .p78. 3.8737935
14 Q61                    ~1     1     1     .p79. 4.2749067
15 Q62                    ~1     1     1     .p80. 4.3970982
16 Q63                    ~1     1     1     .p81. 4.4018504
17 Q64                    ~1     1     1     .p82. 4.2882078
18 Q65                    ~1     1     1     .p83. 4.1516964
19 Q66                    ~1     1     1     .p84. 4.0176479
20 Q67                    ~1     1     1     .p85. 4.1646977
21 Q68                    ~1     1     1     .p86. 3.8268969
22 Q69                    ~1     1     1     .p87. 3.9635777
23 Q70                    ~1     1     1     .p88. 3.8762864
24 Q71                    ~1     1     1     .p89. 3.8028235
25 Q72                    ~1     1     1     .p90. 3.8508281
26 Consciencia_Emocional  ~1     1     1           0.0000000
27 Regulacao_Emocional    ~1     1     1           0.0000000
28 Consciencia_Social     ~1     1     1           0.0000000
29 Autocontrole_Emocional ~1     1     1           0.0000000
30 Criatividade_Emocional ~1     1     1           0.0000000
31 Q48                    ~1     2     2     .p66. 3.9831675
32 Q49                    ~1     2     2     .p67. 3.7717275
33 Q50                    ~1     2     2     .p68. 3.8169089
34 Q51                    ~1     2     2     .p69. 4.0824878
35 Q52                    ~1     2     2     .p70. 3.9618370
36 Q53                    ~1     2     2     .p71. 3.8099404
37 Q54                    ~1     2     2     .p72. 4.0902097
38 Q55                    ~1     2     2     .p73. 3.5255858
39 Q56                    ~1     2     2     .p74. 3.7753546
40 Q57                    ~1     2     2     .p75. 3.3889286
41 Q58                    ~1     2     2     .p76. 4.0758117
42 Q59                    ~1     2     2     .p77. 3.7849402
43 Q60                    ~1     2     2     .p78. 3.8737935
44 Q61                    ~1     2     2     .p79. 4.2749067
45 Q62                    ~1     2     2     .p80. 4.3970982
46 Q63                    ~1     2     2     .p81. 4.4018504
47 Q64                    ~1     2     2     .p82. 4.2882078
48 Q65                    ~1     2     2     .p83. 4.1516964
49 Q66                    ~1     2     2     .p84. 4.0176479
50 Q67                    ~1     2     2     .p85. 4.1646977
51 Q68                    ~1     2     2     .p86. 3.8268969
52 Q69                    ~1     2     2     .p87. 3.9635777
53 Q70                    ~1     2     2     .p88. 3.8762864
54 Q71                    ~1     2     2     .p89. 3.8028235
55 Q72                    ~1     2     2     .p90. 3.8508281
56 Consciencia_Emocional  ~1     2     2           0.2373690
57 Regulacao_Emocional    ~1     2     2           0.3043762
58 Consciencia_Social     ~1     2     2           0.1904483
59 Autocontrole_Emocional ~1     2     2           0.1320373
60 Criatividade_Emocional ~1     2     2           0.2795003

## 9️⃣ MODELO MULTIGRUPO BAYESIANO FINAL

In [38]:
parameterEstimates(
  fit_bayes_gender,
  ci = TRUE,
  level = 0.95
) %>%
  filter(op == "~1")

   lhs                    op rhs block group label est
1  Q48                    ~1     1     1     .p66. 3.8576557
2  Q49                    ~1     1     1     .p67. 3.6461467
3  Q50                    ~1     1     1     .p68. 3.7024699
4  Q51                    ~1     1     1     .p69. 3.9574469
5  Q52                    ~1     1     1     .p70. 3.8345217
6  Q53                    ~1     1     1     .p71. 3.6941162
7  Q54                    ~1     1     1     .p72. 3.9685591
8  Q55                    ~1     1     1     .p73. 3.5755639
9  Q56                    ~1     1     1     .p74. 3.8322427
10 Q57                    ~1     1     1     .p75. 3.4407143
11 Q58                    ~1     1     1     .p76. 4.1229465
12 Q59                    ~1     1     1     .p77. 3.8421541
13 Q60                    ~1     1     1     .p78. 3.9286914
14 Q61                    ~1     1     1     .p79. 4.2583489
15 Q62                    ~1     1     1     .p80. 4.3908144
16 Q63                    ~1     1     1     .p81. 4.3908245
17 Q64                    ~1     1     1     .p82. 4.2880043
18 Q65                    ~1     1     1     .p83. 4.0362206
19 Q66                    ~1     1     1     .p84. 3.9125519
20 Q67                    ~1     1     1     .p85. 4.0645375
21 Q68                    ~1     1     1     .p86. 3.7977126
22 Q69                    ~1     1     1     .p87. 3.9527219
23 Q70                    ~1     1     1     .p88. 3.8446116
24 Q71                    ~1     1     1     .p89. 3.7444640
25 Q72                    ~1     1     1     .p90. 3.8276986
26 Consciencia_Emocional  ~1     1     1           0.0000000
27 Regulacao_Emocional    ~1     1     1           0.0000000
28 Consciencia_Social     ~1     1     1           0.0000000
29 Autocontrole_Emocional ~1     1     1           0.0000000
30 Criatividade_Emocional ~1     1     1           0.0000000
31 Q48                    ~1     2     2     .p66. 3.8576557
32 Q49                    ~1     2     2     .p67. 3.6461467
33 Q50                    ~1     2     2     .p68. 3.7024699
34 Q51                    ~1     2     2     .p69. 3.9574469
35 Q52                    ~1     2     2     .p70. 3.8345217
36 Q53                    ~1     2     2     .p71. 3.6941162
37 Q54                    ~1     2     2     .p72. 3.9685591
38 Q55                    ~1     2     2     .p73. 3.5755639
39 Q56                    ~1     2     2     .p74. 3.8322427
40 Q57                    ~1     2     2     .p75. 3.4407143
41 Q58                    ~1     2     2     .p76. 4.1229465
42 Q59                    ~1     2     2     .p77. 3.8421541
43 Q60                    ~1     2     2     .p78. 3.9286914
44 Q61                    ~1     2     2     .p79. 4.2583489
45 Q62                    ~1     2     2     .p80. 4.3908144
46 Q63                    ~1     2     2     .p81. 4.3908245
47 Q64                    ~1     2     2     .p82. 4.2880043
48 Q65                    ~1     2     2     .p83. 4.0362206
49 Q66                    ~1     2     2     .p84. 3.9125519
50 Q67                    ~1     2     2     .p85. 4.0645375
51 Q68                    ~1     2     2     .p86. 3.7977126
52 Q69                    ~1     2     2     .p87. 3.9527219
53 Q70                    ~1     2     2     .p88. 3.8446116
54 Q71                    ~1     2     2     .p89. 3.7444640
55 Q72                    ~1     2     2     .p90. 3.8276986
56 Consciencia_Emocional  ~1     2     2           0.4111311
57 Regulacao_Emocional    ~1     2     2           0.1267415
58 Consciencia_Social     ~1     2     2           0.1481310
59 Autocontrole_Emocional ~1     2     2           0.3140129
60 Criatividade_Emocional ~1     2     2           0.2530097

In [41]:
parameterEstimates(
  fit_bayes_gender,
  ci = TRUE,
  level = 0.95
) %>%
  filter(op == "~1", lhs %in% c(
    "Consciencia_Emocional",
    "Regulacao_Emocional",
    "Consciencia_Social",
    "Autocontrole_Emocional",
    "Criatividade_Emocional"
  ))

   lhs                    op rhs block group label est
1  Consciencia_Emocional  ~1     1     1           0.0000000
2  Regulacao_Emocional    ~1     1     1           0.0000000
3  Consciencia_Social     ~1     1     1           0.0000000
4  Autocontrole_Emocional ~1     1     1           0.0000000
5  Criatividade_Emocional ~1     1     1           0.0000000
6  Consciencia_Emocional  ~1     2     2           0.4111311
7  Regulacao_Emocional    ~1     2     2           0.1267415
8  Consciencia_Social     ~1     2     2           0.1481310
9  Autocontrole_Emocional ~1     2     2           0.3140129
10 Criatividade_Emocional ~1     2     2           0.2530097

In [42]:
parameterEstimates(
  fit_bayes_leader,
  ci = TRUE,
  level = 0.95
) %>%
  filter(op == "~1", lhs %in% c(
    "Consciencia_Emocional",
    "Regulacao_Emocional",
    "Consciencia_Social",
    "Autocontrole_Emocional",
    "Criatividade_Emocional"
  ))

   lhs                    op rhs block group label est
1  Consciencia_Emocional  ~1     1     1           0.0000000
2  Regulacao_Emocional    ~1     1     1           0.0000000
3  Consciencia_Social     ~1     1     1           0.0000000
4  Autocontrole_Emocional ~1     1     1           0.0000000
5  Criatividade_Emocional ~1     1     1           0.0000000
6  Consciencia_Emocional  ~1     2     2           0.2373690
7  Regulacao_Emocional    ~1     2     2           0.3043762
8  Consciencia_Social     ~1     2     2           0.1904483
9  Autocontrole_Emocional ~1     2     2           0.1320373
10 Criatividade_Emocional ~1     2     2           0.2795003

## 🔟 COMPARAÇÃO ENTRE FATORES LATENTES

In [68]:
fatores <- c(
  "Consciencia_Emocional",
  "Regulacao_Emocional",
  "Consciencia_Social",
  "Autocontrole_Emocional",
  "Criatividade_Emocional"
)

In [69]:
comb <- combn(fatores, 2, simplify = FALSE)

In [70]:
contraste_fatores <- function(post, f1, f2) {
  delta <- post[[1]][, paste0(f1, "~1.g2")] -
           post[[1]][, paste0(f2, "~1.g2")]
  
  c(
    Media = mean(delta),
    IC2.5 = quantile(delta, .025),
    IC97.5 = quantile(delta, .975)
  )
}

In [71]:
postG <- blavInspect(fit_bayes_gender, "mcmc")

resultados_genero <- do.call(
  rbind,
  lapply(comb, function(x) contraste_fatores(postG, x[1], x[2]))
)

rownames(resultados_genero) <- sapply(comb, paste, collapse = " - ")
resultados_genero

                                                Media       IC2.5.2.5%
Consciencia_Emocional - Regulacao_Emocional      0.28361950  0.07828839
Consciencia_Emocional - Consciencia_Social       0.26266816  0.06044979
Consciencia_Emocional - Autocontrole_Emocional   0.09693114 -0.13957232
Consciencia_Emocional - Criatividade_Emocional   0.15689357 -0.02854064
Regulacao_Emocional - Consciencia_Social        -0.02095134 -0.21681097
Regulacao_Emocional - Autocontrole_Emocional    -0.18668837 -0.40735008
Regulacao_Emocional - Criatividade_Emocional    -0.12672593 -0.31596207
Consciencia_Social - Autocontrole_Emocional     -0.16573702 -0.35008907
Consciencia_Social - Criatividade_Emocional     -0.10577459 -0.27027600
Autocontrole_Emocional - Criatividade_Emocional  0.05996243 -0.15287317
                                                IC97.5.97.5%
Consciencia_Emocional - Regulacao_Emocional     0.49362388
Consciencia_Emocional - Consciencia_Social      0.45870541
Consciencia_Emocional - Autocontrole_Emocional  0.32828950
Consciencia_Emocional - Criatividade_Emocional  0.34604807
Regulacao_Emocional - Consciencia_Social        0.17090659
Regulacao_Emocional - Autocontrole_Emocional    0.03937597
Regulacao_Emocional - Criatividade_Emocional    0.06421700
Consciencia_Social - Autocontrole_Emocional     0.01568614
Consciencia_Social - Criatividade_Emocional     0.05781885
Autocontrole_Emocional - Criatividade_Emocional 0.26708482

In [72]:
postL <- blavInspect(fit_bayes_leader, "mcmc")

resultados_lideranca <- do.call(
  rbind,
  lapply(comb, function(x) contraste_fatores(postL, x[1], x[2]))
)

rownames(resultados_lideranca) <- sapply(comb, paste, collapse = " - ")
resultados_lideranca

                                                Media       IC2.5.2.5%
Consciencia_Emocional - Regulacao_Emocional     -0.06596774 -0.28884415
Consciencia_Emocional - Consciencia_Social       0.04630571 -0.14901031
Consciencia_Emocional - Autocontrole_Emocional   0.10610441 -0.12209253
Consciencia_Emocional - Criatividade_Emocional  -0.04215001 -0.22181511
Regulacao_Emocional - Consciencia_Social         0.11227345 -0.08442194
Regulacao_Emocional - Autocontrole_Emocional     0.17207215 -0.06048697
Regulacao_Emocional - Criatividade_Emocional     0.02381773 -0.16309086
Consciencia_Social - Autocontrole_Emocional      0.05979870 -0.12309329
Consciencia_Social - Criatividade_Emocional     -0.08845572 -0.25532149
Autocontrole_Emocional - Criatividade_Emocional -0.14825442 -0.35829645
                                                IC97.5.97.5%
Consciencia_Emocional - Regulacao_Emocional     0.14748613
Consciencia_Emocional - Consciencia_Social      0.24551132
Consciencia_Emocional - Autocontrole_Emocional  0.33895944
Consciencia_Emocional - Criatividade_Emocional  0.13552809
Regulacao_Emocional - Consciencia_Social        0.31136395
Regulacao_Emocional - Autocontrole_Emocional    0.39790987
Regulacao_Emocional - Criatividade_Emocional    0.21382300
Consciencia_Social - Autocontrole_Emocional     0.24392000
Consciencia_Social - Criatividade_Emocional     0.07845536
Autocontrole_Emocional - Criatividade_Emocional 0.06525988

In [73]:
diff_diff_fatores <- function(postG, postL, f1, f2) {
  
  # diferença entre fatores – mulheres
  delta_mulheres <- postG[[1]][, paste0(f1, "~1.g2")] -
                    postG[[1]][, paste0(f2, "~1.g2")]
  
  # diferença entre fatores – líderes
  delta_lideres <- postL[[1]][, paste0(f1, "~1.g2")] -
                   postL[[1]][, paste0(f2, "~1.g2")]
  
  # diferença das diferenças
  diff_diff <- delta_mulheres - delta_lideres
  
  c(
    Media = mean(diff_diff),
    IC2.5 = quantile(diff_diff, .025),
    IC97.5 = quantile(diff_diff, .975)
  )
}

In [74]:
fatores <- c(
  "Consciencia_Emocional",
  "Regulacao_Emocional",
  "Consciencia_Social",
  "Autocontrole_Emocional",
  "Criatividade_Emocional"
)

comb <- combn(fatores, 2, simplify = FALSE)

In [75]:
postG <- blavInspect(fit_bayes_gender, "mcmc")
postL <- blavInspect(fit_bayes_leader, "mcmc")

resultados_diffdiff <- do.call(
  rbind,
  lapply(comb, function(x)
    diff_diff_fatores(postG, postL, x[1], x[2]))
)

rownames(resultados_diffdiff) <- sapply(comb, paste, collapse = " − ")

resultados_diffdiff

                                                Media        IC2.5.2.5%
Consciencia_Emocional − Regulacao_Emocional      0.349587245  0.04713554
Consciencia_Emocional − Consciencia_Social       0.216362451 -0.06259912
Consciencia_Emocional − Autocontrole_Emocional  -0.009173272 -0.34744898
Consciencia_Emocional − Criatividade_Emocional   0.199043581 -0.05481080
Regulacao_Emocional − Consciencia_Social        -0.133224794 -0.40482626
Regulacao_Emocional − Autocontrole_Emocional    -0.358760517 -0.67613651
Regulacao_Emocional − Criatividade_Emocional    -0.150543664 -0.41304562
Consciencia_Social − Autocontrole_Emocional     -0.225535723 -0.47968001
Consciencia_Social − Criatividade_Emocional     -0.017318870 -0.25245790
Autocontrole_Emocional − Criatividade_Emocional  0.208216853 -0.09220603
                                                IC97.5.97.5%
Consciencia_Emocional − Regulacao_Emocional      0.65958184
Consciencia_Emocional − Consciencia_Social       0.49605138
Consciencia_Emocional − Autocontrole_Emocional   0.32323485
Consciencia_Emocional − Criatividade_Emocional   0.45663863
Regulacao_Emocional − Consciencia_Social         0.14273136
Regulacao_Emocional − Autocontrole_Emocional    -0.03561163
Regulacao_Emocional − Criatividade_Emocional     0.12453513
Consciencia_Social − Autocontrole_Emocional      0.02899927
Consciencia_Social − Criatividade_Emocional      0.22132526
Autocontrole_Emocional − Criatividade_Emocional  0.50358290

In [77]:
resultados_diffdiff <- as.data.frame(resultados_diffdiff)

resultados_diffdiff$Robusto <-
  !(resultados_diffdiff$IC2.5 < 0 & resultados_diffdiff$IC97.5 > 0)

resultados_diffdiff

                                                Media        IC2.5.2.5%
Consciencia_Emocional − Regulacao_Emocional      0.349587245  0.04713554
Consciencia_Emocional − Consciencia_Social       0.216362451 -0.06259912
Consciencia_Emocional − Autocontrole_Emocional  -0.009173272 -0.34744898
Consciencia_Emocional − Criatividade_Emocional   0.199043581 -0.05481080
Regulacao_Emocional − Consciencia_Social        -0.133224794 -0.40482626
Regulacao_Emocional − Autocontrole_Emocional    -0.358760517 -0.67613651
Regulacao_Emocional − Criatividade_Emocional    -0.150543664 -0.41304562
Consciencia_Social − Autocontrole_Emocional     -0.225535723 -0.47968001
Consciencia_Social − Criatividade_Emocional     -0.017318870 -0.25245790
Autocontrole_Emocional − Criatividade_Emocional  0.208216853 -0.09220603
                                                IC97.5.97.5% Robusto
Consciencia_Emocional − Regulacao_Emocional      0.65958184   TRUE
Consciencia_Emocional − Consciencia_Social       0.49605138  FALSE
Consciencia_Emocional − Autocontrole_Emocional   0.32323485  FALSE
Consciencia_Emocional − Criatividade_Emocional   0.45663863  FALSE
Regulacao_Emocional − Consciencia_Social         0.14273136  FALSE
Regulacao_Emocional − Autocontrole_Emocional    -0.03561163   TRUE
Regulacao_Emocional − Criatividade_Emocional     0.12453513  FALSE
Consciencia_Social − Autocontrole_Emocional      0.02899927  FALSE
Consciencia_Social − Criatividade_Emocional      0.22132526  FALSE
Autocontrole_Emocional − Criatividade_Emocional  0.50358290  FALSE